### ISSUE TITLE
Feature request: developer FAQ

### ISSUE THREAD

**Issue by Swaagie** [WebThingsIO/gateway#1279]
Would it be useful to add a small list of FAQs to the developer menu?

For example, logs showed me the gateway had no access to `/dev/ttyACM0`. Rather than running the process as `sudo` which will result in a lot of written files having root only permissions. Adding the `$USER` to the `dialout` group will resolve the issue. These one of easy issues can be annoying and 'fixes' might not always be correct. Having some FAQ could improve the developer experience.

Happy to contribute this work, with some basic first questions being answered. These could then later be extended or even made 'smart' by parsing log files.

**Comment by benfrancis** [comment]
We could consider this as part of an in-UI help feature (see https://github.com/mozilla-iot/gateway/issues/677), but for developer FAQs it might be more appropriate to create a [wiki page](https://github.com/mozilla-iot/wiki/wiki) for that. We could possibly link to that wiki page from the UI as part of the in-UI help.

**Comment by mrstegeman** [comment]
https://github.com/WebThingsIO/wiki/wiki#general-1
