### ISSUE TITLE
Suggestions on adding build instructions for Fedora IoT

### ISSUE THREAD

**Issue by ric96** [WebThingsIO/gateway#1504]
I recently tested building gateway on Fedora IoT. I have instructions ready since they are very similar to regular fedora (for the most part just replace dnf with rpm-ostree).

The issue with Fedora IoT is that any new package(sets) install only gets applied once the system reboots, that means, it's very inefficient to install packages separately as we do with the current build instructions because we'll have to reboot after each ```sudo rpm-ostree install pkg``` command.

The connect way to do that would be to install all the packages at once and reboot:
```
$ sudo rpm-ostree install pkg1 pkg2 pkg3...pkgn
$ systemctl reboot
```

My solution is a bit more ambitions, I suggest having separate guides for separate distros and then a "Linux Guide" with the common bits and pieces. Somewhat like [Kodi does](https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md).

I'd like to discuss further...

**Comment by benfrancis** [comment]
I've previously tried, and failed, to split out the README by OS. Open to suggestions on how best to document this.

Note we're also working on some end user documentation using Jekyll. We could consider doing something similar for developer documentation. We also have the [wiki](https://github.com/mozilla-iot/wiki/wiki).

**Comment by ric96** [comment]
Sorry about the delay on this one. I personally think that a Jekyll based solution might be better and easier to navigate with special cases like Fedora IoT having a separate section.
In the meantime I can add the instructions to wiki similar to https://github.com/mozilla-iot/wiki/wiki/Building-the-Raspberry-Pi-gateway-on-the-host
