### ISSUE TITLE
SMS Notifications

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#1626]
As a user I want to create a rule which notifies me by SMS when something happens.

**Comment by flatsiedatsie** [comment]
is this intended to use an SMS service? Or will it be able to use connected GSM modems too? Or even connected devices that have this capability? 

For example, I have built a MySensors smart lock with built in SMS functionality, which is exposed to Mozilla Gateway via the MyController-RS project. This smart lock also takes a string-input which, when it changes/updates, is sent as an SMS to the phone number the user has provided (via another string input) to the lock as well. The goal was to have the lock also act as a generalised SMS gateway.

**Comment by benfrancis** [comment]
> is this intended to use an SMS service? Or will it be able to use connected GSM modems too?

It will use an SMS service.

**Comment by benfrancis** [comment]
Requires Firefox Accounts integration, punting.

**Comment by mrstegeman** [comment]
Depends on #1699

**Comment by arist0v** [comment]
i saw this feature, and i don'T know for where you're from, but for me if my gateway could send an email i could send sms too(8195555555@cellprovider.com)  hope it could help

**Comment by flatsiedatsie** [comment]
Another option is to create the [Candle Smart Lock](https://www.candlesmarthome.com/smart-lock) and connect it to the gateway with the MySensors add-on. Then you don't need a cloud service at all.

**Comment by mrstegeman** [comment]
Closing, since this was dependent on FxA. This can be left to an add-on, e.g. Twilio.
