### ISSUE TITLE
Settings  - DNS

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#1648]
As a user I want to manually configure which DNS servers to use.

**Comment by benfrancis** [comment]
Could DNS be in the WAN (Internet) and/or LAN (Home Network) settings You might want to have DNS set by DHCP or have IP set by DHCP and DNS set manually.

**Comment by dhylands** [comment]
On the WAN side you typically use the DNS provided by the ISP via DHCP or you override it to something else. The LAN side normally uses the router as the DNS server, unless it gets something else via DHCP.
Ubuntu has the option to specify Manual, full "Automatic (DHCP), or "Automatcic (DHCP Addresses only) which allows you to get IP addresses and gateway via DHCP but use DNS entered manually,
