### ISSUE TITLE
Apache Proxy Settings

### ISSUE THREAD

**Issue by cwmke** [WebThingsIO/gateway#1806]
First off, thanks for this great project! Very simple to get it up and running. During setup, I skipped the Mozilla subdomain setup in order to integrate the gateway with my existing Apache server and use letsencrypt certificates. I'm using the below settings which connects the pi to my server but after logging in all of the things are listed as disconnected. When I connect with the LAN ip, everything works fine.

Any ideas for getting this working?

```
        ProxyRequests On
        ProxyPreserveHost Off
        ProxyPass / http://192.168.1.20/      
        ProxyPassReverse / http://192.168.1.20/

**Comment by mrstegeman** [comment]
You’ll need to also proxy WebSocket connections. Not sure offhand what the Apache magic is for that.

**Comment by cwmke** [comment]
With the below it seems to mostly work. I can click buttons to pause/play but the "Disconnected" message is still below. Thanks for the WebSocket pointer.

```
        ProxyRequests Off
        ProxyPreserveHost On
        ProxyPass / http://192.168.1.20/      
        ProxyPassReverse / http://192.168.1.20/
        ProxyPass / ws://192.168.1.20/      
        ProxyPassReverse / ws://192.168.1.20/

**Comment by mrstegeman** [comment]
The problem, I believe, is that websocket connections come in on the same path/port as the other http connections. The following config got me closer, in that the request gets a 101 status response, but the gateway crashes after that.

```
Listen 80
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
LoadModule rewrite_module modules/mod_rewrite.so

<VirtualHost *:80>
  ProxyRequests Off
  ProxyPreserveHost On

  RewriteEngine on
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /(.*) ws://${DESTINATION_IP}/$1 [P,L]

  ProxyPass / http://${DESTINATION_IP}/
  ProxyPassReverse / http://${DESTINATION_IP}/
</VirtualHost>
```

**Comment by kdickerson** [comment]
Has anyone gotten this to work?

I'm using this configuration:

```
        ProxyPreserveHost on
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule "(.*)" "wss://192.168.7.7$1" [P,L]

        SSLProxyEngine on
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        ProxyPass "/" "https://192.168.7.7/"
        ProxyPassReverse "/" "https://192.168.7.7/"
```

Firefox is showing all websocket requests as successful and Apache is not logging any errors, but something is still missing.  `Things` still show as "Disconnected".

Since nothing is reporting any kind of error, I'm kind of out of ideas on where to dig.

**Comment by eode** [comment]
No answer to this?  I have a need for proxy settings as well -- specifically, I'd like to use the Mozilla-IOT RPI as a router as well.  As-is, this isn't possible since firewall rules are (or seem to be) required.

Help?

**Comment by eode** [comment]
Alternatively -- a different set of firewall rules that's specific to the host the system is running on would work.

**Comment by mrstegeman** [comment]
@eode the only iptables rules the gateway sets up (on the Raspberry Pi) are to redirect ports 80->8080 and 443->4443. Those are not absolutely necessary, just more of a convenience.

**Comment by kdickerson** [comment]
I was missing a `RewriteEngine on` directive just before the `RewriteCond` line in my attempted configuration, however I still haven't gotten it working.

With the rewrite actually running I'm now getting a bunch of error messages in my Apache log like this:

```
[Sat Jan 18 22:05:10.849361 2020] [proxy:error] [pid 13932:tid 140301180057344] (111)Connection refused: AH00957: WSS: attempt to connect to 192.168.7.7:443 (*) failed
[Sat Jan 18 22:05:10.849401 2020] [proxy_wstunnel:error] [pid 13932:tid 140301180057344] [client 192.168.1.1:51814] AH02452: failed to make connection to backend: 192.168.7.7
```

Eventually the RPi dies and reboots.

I thought maybe the Websocket proxy wasn't respecting the SSLProxy config about not verifying the cert (I reordered the rules so those came first).  So I tried doing the Websocket rewrite to `ws://` instead of `wss://` but the errors still occured (just saying `192.168.7.7:80`).

**Comment by mrstegeman** [comment]
Be default, the gateway uses port 8080 for HTTP and 4443 for HTTPS.

**Comment by kdickerson** [comment]
I have tried the following rewrite directives with the same `Connection refused` messages:

```
RewriteRule "(.*)" "ws://192.168.7.7$1" [P,L]
RewriteRule "(.*)" "ws://192.168.7.7:8080$1" [P,L]
RewriteRule "(.*)" "wss://192.168.7.7$1" [P,L]
RewriteRule "(.*)" "wss://192.168.7.7:4443$1" [P,L]
```

I have not been able to figure out how to enable/find any useful logging from the gateway that might shed light on what's happening on its side of these connection attempts.  I don't use Node, so I'm familiar with its configuration & logging capabilities.  Any insight there would be appreciated.

**Comment by mrstegeman** [comment]
Have you tried nginx, by chance? Wondering if that might work better.

**Comment by kdickerson** [comment]
I have not tried nginx, I have several virtualhosts on this Apache config so switching over isn't super convenient.

**Comment by typh289** [comment]
I went trough the same issue, tried in a lot of ways with Apache but always had troubles one way or another, if it may be of help to anyone i ended up using haproxy to handle it and worked out a breeze, had a try also with nginx and there are no troubles as well, Apache looks it can't well handle the ws on the same path

**Comment by mrstegeman** [comment]
Closing, as this isn't really a gateway issue. However, for anyone coming across this, here is what I use for nginx:

```
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;


events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    gzip on;

    map $http_upgrade $proxy_connection {
        default upgrade;
        "" close;
    }

    server {
        listen 80;
        listen 443 ssl http2;
        server_name webthings.example.com;

        ssl_certificate /etc/letsencrypt/live/webthings.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/webthings.example.com/privkey.pem;

        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA!RC4:EECDH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS";

        if ($scheme != "https") {
            return 301 https://$host$request_uri;
        }

        location / {
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $proxy_connection;
            proxy_pass http://192.168.1.100:8080;
        }
    }
}
```
