### ISSUE TITLE
Consider vendor-prefixing custom members of the Thing Description

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#1919]
We currently sneak some vendor-specific properties into the Thing Description for convenience, including:
* `floorplanX`
* `floorplanY`
* `layoutIndex`
* `selectedCapability`
* `iconHref`

If we're going to continue to include these in the Thing Description (so far we haven't come up with a better solution) then I suggest that we should add a vendor prefix to the properties that are not part of the [Web Thing Description](https://iot.mozilla.org/wot/#web-thing-description) specification. e.g. `mozFloorplanX`

**Comment by dhylands** [comment]
Perhaps they should be collected together in a moz dictionary?

**Comment by benfrancis** [comment]
That is an option, which would be currently work quite well as all the vendor-specific properties at the top level. But if we introduce vendor-specific or experimental properties in future at other levels (e.g. part of a Property object) then it might be more clunky. On balance I'm thinking just adding prefixes to individual properties might work better long term.

I'd actually like to make this part of the Web Thing Description specification, and follow the same method as the Web App Manifest does https://w3c.github.io/manifest/#proprietary-extensions

See also https://github.com/mozilla-iot/wot/issues/12

**Comment by benfrancis** [comment]
Duplicate of #2832.
