### ISSUE TITLE
certificate installation bug for new gateway setup

### ISSUE THREAD

**Issue by kgiori** [WebThingsIO/gateway#1960]
installation of a new gateway, using reclaimed subdomain said "Success..." and then the browser window did not redirect to the first user creation but instead gave this error:

`http://172.18.0.133/%3C!DOCTYPE%20html%3E%3Chtml%20lang=%22en%22%3E%3Chead%3E%3Cmeta%20charset=%22utf-8%22%3E%3Ctitle%3EError%3C/title%3E%3C/head%3E%3Cbody%3E%3Cpre%3ETypeError:%20Cannot%20read%20property%20&#39;on&#39;%20of%20null%3Cbr%3E%20&nbsp;%20&nbsp;at%20startHttpsGateway%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:114:1)%3Cbr%3E%20&nbsp;%20&nbsp;at%20Object../src/app.js.TunnelService.switchToHttps%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:403:1)%3Cbr%3E%20&nbsp;%20&nbsp;at%20cb%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)%3Cbr%3E%20&nbsp;%20&nbsp;at%20Object.register%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:195:1)%3Cbr%3E%20&nbsp;%20&nbsp;at%20&lt;anonymous&gt;%3C/pre%3E%3C/body%3E%3C/html%3E`

which I copied from the browser URL bar.

**Comment by hobinjk** [comment]
```html
<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <title>Error</title>
  </head>
  <body>
    <pre>
      TypeError: Cannot read property &#39;on&#39; of null<br>
      &nbsp; &nbsp;at startHttpsGateway (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:114:1)<br>
      &nbsp; &nbsp;at Object../src/app.js.TunnelService.switchToHttps (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:403:1)<br>
      &nbsp; &nbsp;at cb (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)<br>
      &nbsp; &nbsp;at Object.register (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:195:1)<br>
      &nbsp; &nbsp;at &lt;anonymous&gt;
    </pre>
  </body>
</html>
```

**Comment by hobinjk** [comment]
Likely a race condition where `TunnelService.hasCertificates()` returns false during the call to `createHttpsServer` in `startHttpsGateway`

**Comment by OldrichKruchna** [comment]
I am not sure if it's connected but during the instalation I ran into this issue as well. At the end I've somehow made it to the end, but now I can not join to the gateway remotely.
`https://{username}.mozilla-iot.org/` does not work, because the certificate is not valid. Can be those issues connected? Any idea how should I proceed?

**Comment by mrstegeman** [comment]
What's the certificate issue you're getting?

**Comment by OldrichKruchna** [comment]
If I open the website in the Firefox and open the certificates details:
![image](https://user-images.githubusercontent.com/9460898/60421694-a38ba000-9bea-11e9-89ae-44b60f891f6b.png)

If I hit the URL with curl, then there is SSL routines error:
```
$ curl https://oldcrew.mozilla-iot.org/
$ curl: (35) error:14004419:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert access denied
```

**Comment by mrstegeman** [comment]
That error occurs when your gateway is not connected to the tunnel. Try connecting to https://gateway.local to see if your gateway is at least running.

**Comment by OldrichKruchna** [comment]
That works without any problems. I've tried to boot the gateway in different network in order to see if it's not blocked by the network settings somehow, but it never worked out.

**Comment by mrstegeman** [comment]
When you connected to gateway.local, did it stay on http or did it switch to https?

**Comment by OldrichKruchna** [comment]
Just http works, for the https is the same issue as for the remote domain.

**Comment by mrstegeman** [comment]
It seems like you may not have made it through certificate generation. On the Pi, do you have files in `~/.mozilla-iot/ssl`?

**Comment by OldrichKruchna** [comment]
Nope, this folder is completely empty.

**Comment by mrstegeman** [comment]
On the pi, run the following:

```bash
rm -rf ~/.mozilla-iot/ssl
sqlite3 ~/.mozilla-iot/config/db.sqlite3 'DELETE FROM settings WHERE key = "tunneltoken"'
sqlite3 ~/.mozilla-iot/config/db.sqlite3 'DELETE FROM settings WHERE key = "notunnel"'
sudo systemctl restart mozilla-iot-gateway
```

Now, navigate to http://gateway.local and you should (hopefully) be presented with the domain setup screen again

**Comment by OldrichKruchna** [comment]
I did that and I was able to reach the domain setup screen again, but if I fill everything and click the Create button, there is just "Processing..." message, which stays forever, no error in the console, anything. Any idea?

**Comment by mrstegeman** [comment]
That's a known issue. Typically, the registration completes, but that screen never disappears. Try opening your URL in a new tab.

**Comment by OldrichKruchna** [comment]
Tried and does not work, if I open the page in new tab or reload the page fresh setup screen appears, where I again need to fill the domain and email 😔

**Comment by mrstegeman** [comment]
Can you send me the latest `run-app.log.*` file in `~/.mozilla-iot/log`? mstegeman@mozilla.com
