### ISSUE TITLE
Make authorization simpler to use

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2098]
I'm very happy and excited to see that add-ons that add UI functionality are planned for the next release. I'm looking forward to it because it will allow for the creation of a totally new type of functionality. This is how I see it:

**Home IoT Phase 1**
Problem: A wide range of different standards means that users have to have multiple hardware and software touch points.
Solution: Create a system/standardisation/abstraction layer to connect it all.

E.g. 
- The Athom Homey had support for every possible hardware radio.
- The Mozilla Gateway proposes a interoperability standard.
- Toggle on the lights when the user gets home or the sun comes up.

**Home IoT Phase 2**
Problem: The value proposition of "control everything from one place" isn't strong enough for a wider audience.
Solution: Create additional value that can only be derived from the aggregate. Now that the hardware is abstracted and centrally available, "apps" can be built on top of this to allow for more 'high level' functionality.

E.g. 
- Get personal recommendations on which type of washing machine to buy based on your current usage patterns and how much electricity each device uses.
- Have a home security 'app' that allows you to monitor a collection of devices from different manufacturers, as well as external sources such as police warnings, and mold them into one feature with one central UI.
- An app that learns the heating coefficients of the different rooms in the house (they all cool down in a different speed), takes into account the humidity levels and has access to a humidifier, and uses all this to optimally manage the climate.
- A smart virtual alarm clock app that slowly wakes you up by raising the brightness of the lights, opening curtains and playing music, taking into account the motion level in bed to figure out in which sleep cycle the occupants are.

To get to this _gateway as a platform_ phase, I feel that on top of allowing add-ons to bring a UI, they may also need more access to the complete ecosystem of devices.

In other words, the user would need to have control over permissions of these add-ons. 

Currently authorizations are quite difficult to use:

1. There is an asymmetry in the UI where users can find the authorization overview page directly under settings ("one level down"). But if users want to add a new authorization, they need to be brave and look in the developer section ("two levels down"). Apparently, they were split up [by this issue](https://github.com/mozilla-iot/gateway/issues/1053).

2. More importantly, currently the user has to manually copy a long token string into an add-on settings field. See [this issue](https://github.com/mozilla-iot/gateway/issues/2057).

I wanted to open this issue to better understand the overall strategy for authorizations, and to suggest that if add-ons will be allowed to bring a UI, it would also be a good opportunity to streamline and future-proof the 'permissions' system.

**Ideas:**
- Conceptually, creating access for external (network) access via the API could still require copying a string and be a 'developer feature', but giving 'internal' add-ons access could be streamlined in the UI.
- The gateway could copy UI patterns from the mobile phone/app ecosystem. E.g. instead of having to copy a string, the gateway could ask the user which permissions they would allow the 'app' to have when they first open it, and then have an overview of permissions under settings where they can (partially) revoke permissions.
- Add-ons could communicate which permissions they would like to have in their json file, with a small description with each permission explaining why it would like to have it, and how not giving the permission would affect the app.
- It would be great if these 'apps' could also programmatically [create rules](https://github.com/mozilla-iot/gateway/issues/2097). That could be a separate permission.
- If user/privacy features are expanded, then this might also lead to relevant permissions.

Permissions I could imagine:
- Read/write some/all devices
- Allow the add-on to read/write rules
- Allow the add-on to access devices 'owned' by other users. It could ask permission from each individual user before being allow to access their data (e.g. a sensor in a childrens bedroom).
- Allow the add-on to access the internet always / only to update.
- Allow add-on to upload aggregated/personal/sensitive/special categories data.

**User story:**
As a user I'd like to give 'apps' permissions to monitor/toggle my devices in a WYSIWYG way. As a user I would like to be able to partially revoke these permissions.

**Comment by flatsiedatsie** [comment]
Is there any chance that the coming version (0.10.0) will make it easier for add-ons to gain access to all the devices in some way? Will it still be necessary for users to copy a string into the add-on settings?

**Comment by mrstegeman** [comment]
Probably will not be in 0.10.

**Comment by flatsiedatsie** [comment]
Thanks.

**Comment by mrstegeman** [comment]
I wonder if we could just generate a unique OAuth token when an add-on is installed, and pass it down to the add-on. Maybe that could be done for [service add-ons](https://github.com/mozilla-iot/gateway/issues/1840)?

**Comment by flatsiedatsie** [comment]
That would be great!

**Comment by mrstegeman** [comment]
Closing this in favor of #2249.
