### ISSUE TITLE
Snap Package

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2147]
As a user I want the gateway software to be available as a snap package so I can easily install it on my existing Linux computer.

This will involve creating a [snapcraft.yaml](https://snapcraft.io/docs/snapcraft-yaml-reference) file to generate a [snap package](https://snapcraft.io/docs) which can be installed on Linux, but also later bundled with an [Ubuntu Core based OS image](https://github.com/WebThingsIO/gateway/issues/3139).

**Comment by benfrancis** [comment]
https://github.com/mozilla-iot/gateway/pull/2124

**Comment by petre2dor** [comment]
@benfrancis is this story holding up the release of 0.10?

**Comment by benfrancis** [comment]
No it's not really blocking the release, we can always package it after the Raspberry Pi 0.10 image has been released. I'm interested in looking at official apt (and possibly rpm) packages too after the main 0.10 release is out the way.
