### ISSUE TITLE
wish: Default actions values

### ISSUE THREAD

**Issue by rzr** [WebThingsIO/gateway#2504]
Hi,

Is it desirable to add default value in action's metadata ?
Prefiled values would make UI faster to be used

If OK, I fill submit a patch that add this feature in this file:
gateway/static/js/views/action-input-form.js

Note to self, there might be an other problem with numbers type and enums...

**Comment by mrstegeman** [comment]
That's fine by me.

**Comment by rzr** [comment]
yes I confirm this issue no more relevant
