### ISSUE TITLE
Gateway crashes about weekly

### ISSUE THREAD

**Issue by vlinder** [WebThingsIO/gateway#2579]
I have an issue where I have to power cycle the gateway a few days apart because it becomes unresponsive. It won't answer neither on the web ui, ssh or ping.

Sometimes the rules still work with the zigbee addon tough. I have a motion sensor that triggers a lamp and it usually works some additional time after the gateway itself has become unresponsive.

I also see temperature spikes, suddenly jumping up 10 degrees C and not coming back down. Can attach screenshots of this from the log.

Have tried disabling all addons except the zigbee but still happens with same frequency.

Edit:
Should have mentioned that I run this on a Raspberry Pi 3, with a sandisk ultra sd card.

**Comment by mrstegeman** [comment]
Is there anything in the log, i.e. `~/.mozilla-iot/log/run-app.log`? There may also be a `crash.log` file in that directory.
