### ISSUE TITLE
What happens when the Gateway is offline?

### ISSUE THREAD

**Issue by x0tester0x** [WebThingsIO/gateway#2581]
When the gateway is offline, will the things keep their configuration?

Example: When I configure a switch to turn on and off the light at specific times during the day, will the switch do this also when the gateway is not reachable or the switch has no connection to a network?

**Comment by mrstegeman** [comment]
It depends on what you mean by "offline", and on what devices you have.

* If your gateway is _off_:
    * It can't control anything.
* If your gateway is _on_, but has no _internet connection_ (e.g. can't reach google.com):
    * If all of your devices are non-Wi-Fi (e.g. Zigbee, Z-Wave, etc.), things will continue working just fine.
    * If some/all of your devices are Wi-Fi based... it depends. Some devices require an internet connection to work, which means the gateway will need an internet connection to control them.
* If your gateway is _on_, but has no _network connection_ (e.g. not connected via Wi-Fi or Ethernet):
    * If all of your devices are non-Wi-Fi (e.g. Zigbee, Z-Wave, etc.), things will continue working just fine.
    * If some/all of your devices are Wi-Fi based, the gateway can't control them.

**Comment by x0tester0x** [comment]
Ok so when the gateway is off, the devices don't have a configuration saved for example a schedule when to turn on or off a lamp, correct?

So only the gateway knows when a devices has to do something, correct?

**Comment by mrstegeman** [comment]
Yes, that’s correct.
