### ISSUE TITLE
Missing id level fluent.js

### ISSUE THREAD

**Issue by madb1lly** [WebThingsIO/gateway#2584]
Hi all,

Another error from the Devtools console when loading the Gateway UI:
```
Missing id level fluent.js:120:12
Missing id level fluent.js:137:12
Missing id level fluent.js:120:12
Missing id level fluent.js:137:12
Missing id level fluent.js:120:12
Missing id level fluent.js:137:12
```
Does anyone else get this? Anything to worry about? Could it be causing the Gateway UI slowdown I experience?

Cheers 🙂

**Comment by mrstegeman** [comment]
What device is causing this issue? Can you break in that error and see what’s generating it?

**Comment by madb1lly** [comment]
Hi @mrstegeman,

The error can't be expanded and I've not worked out how to dig in further through the console or the debugger. The fact that the page runs so slowly also makes it difficult. Any tips on how to proceed?

There are six of these messages, in two sets - three point to one part of fluent.js and the other three point to another part. I suspect that these errors originate from my Arduino WebThings because I have two sets of three identical (or almost identical ones). One type of WebThing's code is here: https://github.com/madb1lly/ESP8266-BME280-WebThing and the other I need to upload.

Cheers 🙂

**Comment by mrstegeman** [comment]
I don’t see anything about “level” in that webthing BC so it must be in the other.
