### ISSUE TITLE
Expose Gateway JS Libraries to Extensions

### ISSUE THREAD

**Issue by damooooooooooh** [WebThingsIO/gateway#2595]
Hi, I'm developing an extension and would like to use the SchemaForm library shipped with the gateway.  We can access the Extension class via the window.Extension reference however I'd like to be able to use window.SchemaForm or similar to access common javascript features.  Is it possible or against the design principles?

It feels counterproductive shipping another schemaform component with the extension.

**Comment by mrstegeman** [comment]
This is certainly possible on a case-by-case basis. SchemaForm is self-contained enough that we should be able to open it up for developer access. Are there other components that you need access to?

**Comment by damooooooooooh** [comment]
I hope I'm not being puristic, but reusing common components like schemaform may improve the consistency or enforce some design principles and probably the performance of the UI as more extensions come onboard.  I haven't looked into anything else right now.  Thanks!
