### ISSUE TITLE
Safari doesn't render input color in this case

### ISSUE THREAD

**Issue by hcientist** [WebThingsIO/gateway#2604]
Neither desktop nor mobile Safari (`Version 14.0 (15610.1.28.1.9, 15610)` and `Version 14.0 Mobile 15E148 Safari 604.1` respectively) render [this input](https://github.com/WebThingsIO/gateway/blob/0d0fc3c88785a113637b765ee1ff79b2480ccdc2/static/js/components/property/color.js#L53) as a color selector and instead show an input text. I have not tracked down the reason. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color renders fine as a color color selector on desktop and mobile
https://caniuse.com/input-color says we're in the clear. 

Unfounded hypothesis: shadowDOM issues 🤷

**Comment by mrstegeman** [comment]
I'm not so sure the shadow DOM is the issue. On the MDN page you referenced, the example is also withing a shadow DOM but it works fine.

**Comment by hcientist** [comment]
How'd you figure out the issue @mrstegeman ?? is it documented in the webs somewhere? great job and thanks!

**Comment by mrstegeman** [comment]
Haha lots of really frustrating trial and error.
