### ISSUE TITLE
Update Wordmark

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2613]
Change Mozilla WebThings Gateway logo to WebThings logo.

SVG assets incoming...

**Comment by benfrancis** [comment]
Different options for new branding. My preference is either option 4 or 5.

Note the updated "Things" icon in option 4, because there's something jarring about having two of the same icon next to each other.

![menu_branding_options](https://user-images.githubusercontent.com/552417/99258213-20cfa900-2810-11eb-9097-31e2c0948a64.png)

**Comment by kgiori** [comment]
I actually like 9 (and 10 - left bottom). On smaller screens having the logo and label of "WebThings Gateway" on top would take too much real estate and make things appear too crowded I suspect.

**Comment by benfrancis** [comment]
> On smaller screens having the logo and label of "WebThings Gateway" on top would take too much real estate and make things appear too crowded I suspect.

Actually I think that's the downside of 9. The reason we stopped putting the logo in a fixed position bottom left in many parts of the UI was that on small screens it tends to overlap with things awkwardly. I think 9 is probably the worst option for small screens :(

Currently 5 and 6 seem most popular based on feedback (but the bottom left hand option for the welcome screen).

**Comment by benfrancis** [comment]
Conclusion was option no. 6 (WebThings Gateway wordmark) for the main menu and the bottom left option (WebThings Gateway lockup) for the setup screens.
