### ISSUE TITLE
Question - Connecting a zigbee bridge 

### ISSUE THREAD

**Issue by rafamedina** [WebThingsIO/gateway#2618]
I'd like to what's the best way to connect a ZigBee bridge. The zigbee plugin seems it's looking for the usb adapter.
Thanks

**Comment by mrstegeman** [comment]
What kind of bridge?

**Comment by rafamedina** [comment]
The Sonoff Zigbee Bridge

**Comment by mrstegeman** [comment]
Ah, this would require a separate add-on. This is the case for Philips Hue and Tradfri as well.
