### ISSUE TITLE
Access Sqlite3 database on a docker gateway

### ISSUE THREAD

**Issue by apeiris** [WebThingsIO/gateway#2642]
I have been running the gateway  on a Windows10 docker container for a while. 
How do I access the SQLite3 database on this (docker) environment.

**Comment by mrstegeman** [comment]
Did you share in a volume to `/home/node/.mozilla-iot`? If so, your database is located inside that directory/volume at `config/db.sqlite3`.

**Comment by apeiris** [comment]
> Did you share in a volume to `/home/node/.mozilla-iot`? If so, your database is located inside that directory/volume at `config/db.sqlite3`.

**Comment by apeiris** [comment]
@mrstegeman , Thanks.. Got what I was looking for..
