### ISSUE TITLE
Light fade slope

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2657]
On the Lifx app, it's possible to set a slope on the brightness of a bulb through the day. It's convenient when doing a morning wakeup light. 
At the moment, the Gateway doesn't allow this and we are forced to create hundreds of rules to achieve the same thing.
It would be great if the app could manage to have long fade times on both bulbs and dimmers.

**Comment by mrstegeman** [comment]
This would use the [FadeAction](https://webthings.io/schemas/#FadeAction) schema. We just don't have a fancy implementation for it in the UI. Individual add-ons need to add this capability.
