### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by raspberryuser** [WebThingsIO/gateway#2668]
I am just a webthings gateway user and I just updated my gateway from version 0.12 to 1.0.0. When I access the gateway via internet there is now a certificate issue since the gateway domain is now xxx.webthings.io but the Let's Encrypt SSL certificate is still issued for xxx.mozilla-iot.org. This was not updated. Therefore the certificate is invalid. It will be re-issued automatically not before January. How can I fix this now? I just have very basic knowledge about my Raspberry Pi. Many thanks for your support.

**Comment by benfrancis** [comment]
Hi @raspberryuser, sorry to hear you're having problems. Can you confirm that you registered for your new xxx.webthings.io subdomain using the transition UI as described on this wiki page? https://github.com/WebThingsIO/wiki/wiki/WebThings-Gateway-Transition-UI

If so, your gateway should automatically have been issued a new certificate as part of that transition process.

Can you provide more details on the error you are seeing?

Thanks

**Comment by raspberryuser** [comment]
Hi,
Yes I registered using the transition UI. When I registered there was an error message after some time. It said that the subdomain is not available. I tried again and somehow the transition process was finished. After that my gateway was accessable via the new xxx.webthings.io subdomain. Everything is working. Just the certificate seems to be the old one and I don't know how I can renew it manually for the correct domain.

**Comment by raspberryuser** [comment]
![CertificateError](https://user-images.githubusercontent.com/75430443/101025542-0585cd00-3576-11eb-8889-9573b88a0376.PNG)

**Comment by raspberryuser** [comment]
I saved an complete image of the micro SD card before I did the update. Should I restart the gateway on my Raspberry Pi with the version 0.12 and do the transition process once again? Is it then possible to reclaim my already working new subdomain ...webthings.io during that process?

**Comment by benfrancis** [comment]
@raspberryuser Thanks for the additional information. @mrstegeman Do you have any idea what's going on here?

> Should I restart the gateway on my Raspberry Pi with the version 0.12 and do the transition process once again? Is it then possible to reclaim my already working new subdomain ...webthings.io during that process?

No don't do that, you won't be able to use the same webthings.io subdomain if you use the transition UI for a second time, only if you install the gateway again from scratch and use the first time setup UI. Stand by and we'll look into this a bit further.

**Comment by mrstegeman** [comment]
It may have just failed to pick up the new certificate. Can you try to just reboot your gateway?

**Comment by raspberryuser** [comment]
I restarted the gateway several times but unfortunately it did not change anything. Is there any way to renew the certificate on the PI manually?

**Comment by mrstegeman** [comment]
Ok, here's what I recommend. Enable SSH on the Pi, if you haven't already, via `Settings -> Developer`. Then SSH into your Pi with username `pi` and password `raspberry`. Then, run the following:

```sh
sudo systemctl stop mozilla-iot-gateway
sudo systemctl stop webthings-gateway
cd ~/webthings/gateway
./tools/remove-tunnel-token.sh
sudo systemctl start webthings-gateway
```

After that, browse to `http://gateway.local` (or the IP address of your Pi). You should be presented with the subdomain setup screen. Fill in the same subdomain and email you chose during the transition, then follow the prompts to reclaim your domain.

**Comment by raspberryuser** [comment]
This worked perfectly! Many, many thanks for your great support. Have a nice evening.
