### ISSUE TITLE
0.12 gateway stopped working

### ISSUE THREAD

**Issue by GFPar** [WebThingsIO/gateway#2669]
Hello - starting yesterday, my 0.12  gateway has failed and no devices are found/connected. Following a reboot, there are just a mass of errors statements. 

I know there is an update to 1.0 coming, on the Status/Updates page is see that the 'Update' is there. After clicking on it, it hangs as 'in process' - for hours - with no progress

I assume the issue i am encountering is related to the update? Any help will be appreciated.

I am running Buster and i installed the gateway (0.12) through the Docker image.

**Comment by mrstegeman** [comment]
If you're using the Docker image, you shouldn't be updating through the UI. You should just pull the latest Docker image, now available here: https://hub.docker.com/r/webthingsio/gateway

**Comment by GFPar** [comment]
Hello, thanks for your response. Just so that I am clear (i don't want to screw anything up...)

I initially installed the gateway using the process described on the page : https://github.com/WebThingsIO/gateway

When i reinstall, do i only need to '$ git clone https://github.com/WebThingsIO/gateway.git' and then go through the install process as laid on the page above?

**Comment by mrstegeman** [comment]
I’m confused. I thought you said you used the Docker image?

**Comment by GFPar** [comment]
Sorry, i probably gave the wrong information. I had an existing Pi and installed the gateway through the approach detailed on the page referenced above. Sorry for the confusion.

**Comment by mrstegeman** [comment]
Ah! That makes more sense now. The update functionality is only supported in the Raspbian image that we provide, so I honestly don’t know what state your Pi is in right now. I would recommend just pulling the latest gateway and rebuilding, as you said.

**Comment by GFPar** [comment]
Ok, let me give that a try. Thanks for your help;  Gerry

**Comment by mrstegeman** [comment]
Closing this issue, but please let me know if you have other questions.
