### ISSUE TITLE
Rules based on external API callback

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2677]
For Plex pass users, it's possible to add URL to external arbitrary code to trigger actions.
These actions can be anything the user would imagine, like "When a press play, dim the livingroom lights" or "When movie ends, resume lighting".
Would it be possible to add a gateway URL to Plex so it could call the gateway to do actions?

**Comment by mrstegeman** [comment]
You can install the brand new Webhook Events add-on.

Check out the README here: https://github.com/WebThingsIO/webhook-events
