### ISSUE TITLE
Update on .deb install is not working

### ISSUE THREAD

**Issue by labou77** [WebThingsIO/gateway#2679]
Hi all,
I have installed webthing manually using deb package from https://github.com/WebThingsIO/gateway-deb 
When I try to update, it just hangs forever see on the picture. 
![image](https://user-images.githubusercontent.com/60555569/101716300-fe295c80-3a6a-11eb-8976-811d9ddb91d4.png)

It seems the manual install is not using the harcoded path used in update process. My webthing is under /opt/webthings-gateway but in /opt/webthings-gateway/tools/check-for-update.js, I see `exec(`./gateway/tools/upgrade.sh ${gatewayUrl} ${nodeModulesUrl}` .
I have tried to edit this file file to get the right directory so it can run and download new version but then, the gateway is not even launching as everything is messed up with pathes and new service with same name is loaded (initially my service is in /lib/systemd/system/webthings-gateway.service)

Is there a way to update in this case?

**Comment by mrstegeman** [comment]
Updating via the UI is not supported with a .deb install. Instead, you'll need to download the latest release here: https://github.com/WebThingsIO/gateway/releases/tag/1.0.0

**Comment by labou77** [comment]
Oh ok thanks @mrstegeman. So if I install the new Deb the same way I did with the first one, it will update and keep my data? Or do I need to uninstall first my current version?

**Comment by mrstegeman** [comment]
Yes, just installing the new one should do the trick.

**Comment by benfrancis** [comment]
@mrstegeman We seem to be getting a lot of reports like this from people who have installed the gateway using something other than the Raspbian image. Could we detect the platform being used and show something different on the update screen for these platforms?
