### ISSUE TITLE
Ubuntu packages do not install.

### ISSUE THREAD

**Issue by clogan2** [WebThingsIO/gateway#2684]
Has anyone actually tried these packages on vanilla ubuntu server?

They refuse to install, citing node >10.0.0 needed no matter what version of node is installed, claiming you have 8.something

**Comment by mrstegeman** [comment]
What Ubuntu version are you using?

**Comment by clogan2** [comment]
Sorry, I tried 20.04.1 as well as 18.04.5

Installed a handful of dependencies that apt couldn't handle: alsa-utils, arping, avahi-daemon, ffmpeg, mosquitto, and sqlite3.

I don't think that libffi6 is available in 20.04, but is included in 18.04. Tried changing versions using nvm, but the installer didn't seem to notice in either OS/package.

**Comment by mrstegeman** [comment]
Ah, yes. I recently fixed several of these issues. What platform (amd64, arm64, etc.) are you installing on? @chas-iot recently built some new .deb packages with the fixes, that he could perhaps share with you.

See here for more information: https://github.com/WebThingsIO/gateway/issues/2681

**Comment by mrstegeman** [comment]
Particularly, running `sudo apt update && sudo apt full-upgrade` seemed to resolve several (but not all) of the installation issues. The new .deb packages solved the rest of the issues.

**Comment by clogan2** [comment]
Couldn't re-produce my earlier issue with node in a new install. It looks like your recent commits solve my problem, I'll build from source. update / full-upgrade didn't work
