### ISSUE TITLE
Groups of rules

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2685]
Hello,
I have only 20 rules at the moment and it seems like I'm lost reading each tile to see what they are. 
On my PC's screen, they fill out the entire screen, and on my phone I can only see 2 rules on the screen, and they exceed the screen width.
I would like to be able to reorder them, and group them in folding panels to better organize the space.

Thanks

**Comment by mrstegeman** [comment]
See #2239.
