### ISSUE TITLE
Use variables values in basic rules conditions

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2691]
Hello, 
I have a variable that change value via a macro.
I would like to be able to use that variable value in my rules.

Thanks!

**Comment by mrstegeman** [comment]
Couldn't you just build up the rules via the Macros extension, rather than the built-in rules engine?

**Comment by soulfire03** [comment]
Sure, I just wanted to avoid deleting all my rules and doing them again.
An automatic convert would be nice someday

**Comment by mrstegeman** [comment]
Seems like something for @bewee to do. 🙂
