### ISSUE TITLE
Tunneling services to Mozilla-Webthings.io

### ISSUE THREAD

**Issue by apeiris** [WebThingsIO/gateway#2693]
I am running webthingsIO gateway(Docker) version 12.18.3.  
The tunneling service I use is from https://xxxxxxxx.mozilla-iot.org/things and it  has not so far prompted me to transition to webthings.io tunneling service as proposed.
sorry I had picked node version instead of gateway which should be webthings-gateway@0.12.0

**Comment by mrstegeman** [comment]
What version of the gateway are you using?

**Comment by apeiris** [comment]
grafana_1            | t=2020-12-28T15:22:33+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table temp_user to temp_user_tmp_qwerty - v1"
webthings-gateway    |
webthings-gateway    | > webthings-gateway@0.12.0 run-only /home/node/mozilla-iot/gateway
webthings-gateway    | > node build/gateway.js
webthings-gateway    |

**Comment by mrstegeman** [comment]
You’re still on 0.12.0. You need to update to 1.0.0 to be able to transition. The Docker image has moved to `webthingsio/gateway`.

**Comment by apeiris** [comment]
Thanks... All good.. apologize any inconvenience caused.
