### ISSUE TITLE
Mysterious 400 error with API

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/gateway#2740]
Just a quick check, since the problem is almost certainly with my own code. 

I just noticed a 400 error when using the PUT command in Voco. But only when updating a string. Setting numeric or boolean values works as normal. Oddly, setting a color on my lights also still works, which is a string.

```
2021-01-20 23:23:48.060 INFO   : voco: Changing property to desired value
2021-01-20 23:23:48.062 INFO   : voco: PUT > api_path = /things/internet-radio/properties/station
2021-01-20 23:23:48.063 INFO   : voco: PUT > json dict = {'station': 'fip'}
2021-01-20 23:23:48.064 INFO   : voco: PUT > self.api_server = http://127.0.0.1:8080
2021-01-20 23:23:48.067 INFO   : voco: API PUT: 400, Bad Request
```

The station name is correct, so I'm not trying to set it to something that doesn't exist. I can also change it through the UI, so it's not suddenly a 'read-only' property.

Is there a smart way to debug this further, and see what the issue is 'under the hood'?

**Comment by kgiori** [comment]
This is an example of why I found the smart assistant UI so useful. If knew that if I could type a string into that UI and it was processed as expected, then I'd be able to say the command too. Would it be possible to create a smart-assistant-like "extension UI" for Voco that let's you type text that is fed directly to the command parser?

**Comment by createcandle** [comment]
@kgiori Good idea, it will be in the next version.

Probably not related, but just in case:
```
Exception in thread Thread-86:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gateway_addon/addon_manager_proxy.py", line 344, in request_fn
    'response': response.to_json()
AttributeError: 'NoneType' object has no attribute 'to_json'
```

**Comment by createcandle** [comment]
@kgiori 
![voco_text](https://user-images.githubusercontent.com/39312291/105379905-9a6b8500-5c0d-11eb-9313-411c2b787e03.png)

**Comment by mrstegeman** [comment]
@createcandle I think your property value is wrong. It should be `Fip`, rather than `fip`. It's case-sensitive, since your property is using an `enum`.

**Comment by kgiori** [comment]
Hey @createcandle, Voco keeps improving -- thanks! But there is one exception (v 2.4.0). The voice response (TTS) is so fast that I can't understand it, even at the slowest (0.5) setting. I'm using a USB speaker/mic. RPi3.

**Comment by createcandle** [comment]
@kgiori Interesting, that's the same issue as another user mentioned. Could you share some of you details (what device, etc) in this issue? 

https://github.com/createcandle/voco/issues/19

The new release also has some small code change to try an mitigate this problem (although it's a shot in the dark for me since I don't have a device that has this issue to test with yet).

@mrstegeman brilliant, that might be it!

**Comment by createcandle** [comment]
I've fixed the issue. Thanks again for the insight.
