### ISSUE TITLE
Error runing gateway on ubuntu

### ISSUE THREAD

**Issue by misomg** [WebThingsIO/gateway#2741]
Hi,
I build gateway on ubuntu 20.04.1 following [https://github.com/WebThingsIO/gateway](https://github.com/WebThingsIO/gateway)

I was able to register and add my sonoff with flashed tasmota. After pc reboot I get an error after attempt to run gateway from its directory with `npm start`  
Any suggestions how properly run gateway on ubuntu will help.

> [Error:] EACCES: permission denied, mkdir '/etc/webthings-gateway/config'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpManualSync (/home/misomg/gateway/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
    at mkdirpNativeSync (/home/misomg/gateway/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
    at Function.mkdirpSync [as sync] (/home/misomg/gateway/node_modules/mkdirp/index.js:21:7)
    at Object.migrate [as default] (/home/misomg/gateway/build/migrate.js:78:26)
    at Object.<anonymous> (/home/misomg/gateway/build/app.js:15:47)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[2021-01-21T18_26_17_955Z-debug.log](https://github.com/WebThingsIO/gateway/files/5851476/2021-01-21T18_26_17_955Z-debug.log)

**Comment by mrstegeman** [comment]
Did you build the Debian package or just a standalone gateway?

**Comment by misomg** [comment]
I think I build standalone gateway. It was from from git clone
[https://github.com/WebThingsIO/gateway#download-and-build-gateway](https://github.com/WebThingsIO/gateway#download-and-build-gateway)

`git clone https://github.com/WebThingsIO/gateway.git`

**Comment by mrstegeman** [comment]
If that's the case, I'm genuinely not sure why it's trying to access `/etc/webthings-gateway`, unless you changed the config file.

**Comment by misomg** [comment]
I build it again, still same error and again no config file change 

> Built at: 01/23/2021 11:12:08 AM
>                  Asset      Size  Chunks             Chunk Names
>      service-worker.js  1.01 KiB       0  [emitted]  service-worker.js
>     service-worker.js_  3.67 KiB       0  [emitted]  service-worker.js
>     Entrypoint service-worker.js = service-worker.js_ service-worker.js
>     [0] ./static/service-worker.js 41 bytes {0} [built]
>     Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/raw-loader/dist/cjs.js??ref--5-1!static/service-worker.js:
>         Entrypoint undefined = extract-text-webpack-plugin-output-filename
>         [0] ./node_modules/raw-loader/dist/cjs.js??ref--5-1!./static/service-worker.js 1.72 KiB {0} [built]
> /home/misomg/gateway/node_modules/mkdirp/lib/mkdirp-manual.js:54
>       throw er
>       ^
> 
> Error: EACCES: permission denied, mkdir '/etc/webthings-gateway/config'
>     at Object.mkdirSync (fs.js:757:3)
>     at mkdirpManualSync (/home/misomg/gateway/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
>     at mkdirpNativeSync (/home/misomg/gateway/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
>     at Function.mkdirpSync [as sync] (/home/misomg/gateway/node_modules/mkdirp/index.js:21:7)
>     at Object.migrate [as default] (/home/misomg/gateway/build/migrate.js:78:26)
>     at Object.<anonymous> (/home/misomg/gateway/build/app.js:38:36)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! webthings-gateway@1.0.0 start: `npm run build && node build/app.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the webthings-gateway@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/misomg/.npm/_logs/2021-01-23T10_12_47_475Z-debug.log
>

**Comment by mrstegeman** [comment]
Is there anything in `~/.webthings/config/local.json`?

**Comment by misomg** [comment]
No, only braces.

```
{
}
```

**Comment by RitvikSardana** [comment]
@misomg 
I am also getting the same error , if you resolve this do tell me.
Thanks.

**Comment by misomg** [comment]
This is not right solution, but I installed gateway on docker and it works fine.

**Comment by RitvikSardana** [comment]
@misomg 
I am using it on raspberri pi with raspbian OS
it worked for the first time, but after that  am getting the same error


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webthings-gateway@1.0.0 start: npm run build && node build/app.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webthings-gateway@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/misomg/.npm/_logs/2021-01-23T10_12_47_475Z-debug.log

Can u help me?

**Comment by misomg** [comment]
For now only solution how to rum gateway was docker, but it should also work on raspbian OS

**Comment by RitvikSardana** [comment]
Exactly it should , but it isn't working, i have done all the steps shown in the readme.md file
Still i am getting this error

**Comment by RitvikSardana** [comment]
@misomg 
Can  u help me with this?
