### ISSUE TITLE
Add-on list uses a different link

### ISSUE THREAD

**Issue by dev-bash** [WebThingsIO/gateway#2756]
I have a fresh install of the gateway on my Pi4 but when i go to add-ons -> + it is solid dark blue

I have checked my logs and on further notice i have found that https://api.mozilla-iot.org:8443/addons doesn't seem to work and I think it should be https://api.webthings.io:8443/addons 

Is there any way I or you can fix this?

Thank you.
PS: i have also posted this on the addon-list GitHub.

**Comment by mrstegeman** [comment]
What version of the gateway did you install?

**Comment by dev-bash** [comment]
I used 0.12

**Comment by mrstegeman** [comment]
That's the problem. 0.12 pointed at the (now defunct) Mozilla infrastructure. Please install 1.0.0 from here: https://webthings.io/gateway/
