### ISSUE TITLE
CSS missing in #2702

### ISSUE THREAD

**Issue by RitvikSardana** [WebThingsIO/gateway#2760]
There is no CSS file in #2702

**Comment by benfrancis** [comment]
@RitvikSardana Can you expand a little? There are CSS files being removed in #2702. Are you saying there are CSS files being removed which shouldn't be?

**Comment by RitvikSardana** [comment]
@benfrancis 
What i am saying is i am trying to change the main UI of the webthings but  I am unable to do so because the  #2702 is not linked with any CSS file
If it is linked to any CSS files then please tell me
or can we talk about my problem on discord or something , it would be easy 
My discord ID is - ritvikdevil

**Comment by madb1lly** [comment]
Hi @RitvikSardana,
You can discuss here: https://chat.mozilla.org/#/room/#iot:mozilla.org
Cheers 🙂
