### ISSUE TITLE
After changing color property, the UI says the color black is selected

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2762]
I've noticed this before, and just noticed it again while working on adding color support to the Zigbee2MQTT addon: if you select a color for your light, after selecting it, the property UI shows the selected color as black. 

The color of the real world lamp is set accurately though, and the capability icon is also the correct color. It's just the property that jumps to black.

![gateway_color_wants_to_be_dark](https://user-images.githubusercontent.com/805405/106330682-efe60880-6283-11eb-96b9-64a70086cfc9.gif)

**Comment by mrstegeman** [comment]
Is the color that's being reported back from the add-on of the form `#123abc`?

**Comment by flatsiedatsie** [comment]
Nope, just an issue with my code, as usual :-)
