### ISSUE TITLE
onOffSwitch shows unexpected behaviour when set to read-only.

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2769]
I have a `onOffSwitch` thing with a read-only `onOffProperty`. It represents a Zigbee IKEA Tradfri ON/OFF button.

When I click on the capability's main icon, it will attempt to toggle the property, and fail.

![tradfri_read_only_button](https://user-images.githubusercontent.com/805405/106517058-464b8500-64d8-11eb-89f7-3ab8437b2f2c.png)

It could be argued that an on/off switch can never be read-only. Then the question becomes: what should be used in this case?

**Comment by mrstegeman** [comment]
It should be represented as a `PushButton`, rather than `OnOffSwitch`.
