### ISSUE TITLE
Addon settings UI doesn't reflect default values on initial load

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2770]
In the `manifest.json` file addons can set the default values. However, after installing an addon and opening the addon settings page, the input fields do not reflect these defaults. 

![gateway_no_defaults](https://user-images.githubusercontent.com/805405/106726469-b1957400-660a-11eb-944b-05aa80e884a4.png)

For example, here the values mentioned in the explanation text should appear in the input fields.

Here is the relevant part from the manifest.json file:

```
  "options": {
    "default": {
      "local_zigbee2mqtt":true,
      "auto_update": true,
      "mqtt": "mqtt://localhost",
      "prefix": "zigbee2mqtt",
      "serial_port": "/dev/ttyACM0",
      "channel": 11,
      "debug": false
    },
    "schema": {
      "type": "object",
      "properties": {
        "local_zigbee2mqtt": {
          "type": "boolean",
          "description": "If enabled, this addon will install and use its own version of Zigbee2MQTT. Disable this if you have already manually installed Zigbee2MQTT on your system."
        },
        "auto_update": {
          "type": "boolean",
          "description": "If the addon manages its own version of Zigbee2MQTT, then enabling this will allow it to try and keep zigbee2MQTT updated to the latest version. This may allow the latest Zigbee devices to be supported. It does come with a small risk that if there would be something wrong with Zigbee2MQTT, then this addon may not start properly."
        },
        "mqtt": {
          "type": "string",
          "description": "Mosquitto or other mqtt server host/port to connect to. Default is 'mqtt://localhost'."
        },
        "prefix": {
          "type": "string",
          "description": "Mqtt topic prefix for zigbee2mqtt. Default is 'zigbee2mqtt'."
        },
        "serial_port": {
          "type": "string",
          "description": "The serial port ID of the zigbee USB stick you are using. Default is '/dev/ttyACM0'."
        },
        "channel": {
          "type": "string",
          "description": "The wireless channel you want to the Zigbee network to use. If you change this, you will have to pair all your devices again. Suggested options are 11, 15, 20, or 25. The default is 11."
        },
        "debug": {
          "type": "boolean",
          "description": "Used to find issues if this addon isn't working properly. If enabled, you can find more details about its functioning in the internal log (found under settings -> development)."
        }
      }
    }
  },
```

This could be confusing to users. It's confusing to me :-)

**Comment by mrstegeman** [comment]
Did you previously have the add-on installed? If so, it would have retained the previous config values, which prevents it from using the defaults. Here's my gateway with a clean installation of that add-on:

![image](https://user-images.githubusercontent.com/457381/106784135-7a1dcc00-65f8-11eb-9296-f84513d8e561.png)

**Comment by flatsiedatsie** [comment]
>  If so, it would have retained the previous config values,

but wouldn't it then show those values? Or does this happen when new options are added to the manifest? I guess the new options then aren't taken in? Good to know.

Actually, that reminds me of a suggestion I've been thinking about: have both a data directory that keeps data after an addon is de-installed, and a data directory whose content is removed when the addon is removed.

**Comment by mrstegeman** [comment]
It would happen with new options. The defaults won't be filled in.

You mean like your other issue? 🙂 https://github.com/WebThingsIO/gateway/issues/2565

**Comment by flatsiedatsie** [comment]
indeed :-)
