### ISSUE TITLE
Can`t skip domain creation step during the registration in docker

### ISSUE THREAD

**Issue by ArtemK123** [WebThingsIO/gateway#2780]
I have tried to use the Mozilla WoT Gateway in docker on my PC.
I have run into a problem during the registration flow - I can`t skip the domain registration step. When I click on the skip button, it tries to redirect me somewhere, but after the redirect, I come to the same domain registration step.
My OS is Windows 10 20H2
My Docker Desktop version is 3.1.0 (with WSL2 is turned on)
I have used Gateway container from https://hub.docker.com/r/webthingsio/gateway/ (webthingsio/gateway:latest, the latest version is 1.0.0 at the moment)
I have started the container with the default configuration, which is listed in the docker hub (usage for Windows).

More formal steps to reproduce:
1. Download and start the container
2. Go to http://localhost:8080
3. Register the account
4. On the domain creation step - try to skip the domain creation

Expected result: Home page of the Mozilla WoT Gateway or some confirmation (I don`t really know what it should be)
Actual result: After the redirect, the same domain registration page is shown
![image](https://user-images.githubusercontent.com/31692671/107128521-05cc7c80-68c7-11eb-9f7a-b1b9c4114a8a.png)

**Comment by mrstegeman** [comment]
Your browser may have something cached. Can you try it in a private browsing window?

**Comment by ArtemK123** [comment]
Hi,
Sure, but I will do it tomorrow. Currently, it is 10:40 pm in my timezone, so I will check at the tomorrow's morning. I will write you about a result something in 10 hours from now. 
But, firstly, could you please tell me what is expected to be when this domain registration step is successfully skipped?

**Comment by mrstegeman** [comment]
You should be taken to a screen to create your first user.

**Comment by ArtemK123** [comment]
Yep, you were right. I have recreated the docker container and tried again in anonymous browser tab - the domain registration is successfully skipped and I am redirected to a user creation. I think, the first time the steps were in wrong order, cause the first page was the user creation step, and then I was redirected to domain creation, which was broken.
Anyway, now it works fine. Thanks for help. I will close this issue.
