### ISSUE TITLE
Question about addons caching values

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2785]
I'm curious if it's possible to update the value of a property in the UI, without having that value be saved/cached/recorded to the data log.

Ideally, I'd love to give users the ability to at any point switch devices between 3 privacy levels:
1. Normal. Gateway show levels in UI, and if there is a log, the data is logged.
2. Medium. Gateway shows up-to-date values in UI, but the data is not logged/remembered/cached.
3. High. Gateway UI does not show incoming data, and also does not log it. It's essentially a 'mute' function for devices.

Option 1 the default, and option 3 is also easy enough to do for an addon (and perhaps system wide some day).

But I'm curious if there is any way to currently enable option 2..
- At the addon level
- At the system level (theoretically)

**Comment by benfrancis** [comment]
- "Medium" is the current default, in that logging is an opt-in feature. Data is only logged if the user explicitly creates a log to log it.
- "Normal" is what users opt into if they want to log data
- "High" is basically disabling a device (but only only the gateway's view of it, for most adapters the device itself would probably still be running as normal)

> I'm curious if it's possible to update the value of a property in the UI, without having that value be saved/cached/recorded to the data log.

My suggestion for how to achieve this would be to have an enable/disable toggle on logs in the same way that there's currently an enable/disable toggle on rules. That way a log can be temporarily paused by disabling it, as is currently possible with rules (e.g. I have a "security alarm" rule which I toggle on when I leave the house and toggle off when I return).

An enable/disable toggle could also be added to devices to achieve the "high" level you describe, though I'm not sure how that actually helps improve privacy while any user can re-enable it at any time. There have been requests to "hide" devices from the Things & Floorplan views, which would essentially achieve the same thing.

**Comment by flatsiedatsie** [comment]
> "Medium" is the current default, in that logging is an opt-in feature

Sorry if I was unclear. I meant that users can switch this off temporarily at any point. I'd like to log values of certain sensors 90% of the time. This is about being able to easily deal with that 10% of the time when I'd like to temporarily change this.

> My suggestion for how to achieve this would be to have an enable/disable toggle on logs 

For my situation I'd love it is this could be done programmatically. My goal is to have a thing with a rotary knob that allows users to set a lot of these privacy levels with a single twist of the knob. For example:
- If friends come over, I'd like to disable video access/recording of cameras as well as measurement/recording of certain sensors for a while with one quick action. Call this a form of 'hospitality' in a smart home.
- If I'm having sex, I'd like bedroom sensors to not be recording, and not have the values visible to others in the home. It's easier to have fun if you're not feeling watched in any way.
- If a cleaner is coming over, I'd like to respect that cleaner's privacy by disabling sensors that might tempt me to act like a big brother. I'd prefer our relationship to be based on trust, and I want to expressly communicate this to that person.

**Comment by benfrancis** [comment]
Thanks for clarifying. I've filed https://github.com/WebThingsIO/gateway/issues/2787 to cover what I think is the core use case here, and which hopefully could provide the first building block for you to create the kind of UI you're describing in an add-on.
