### ISSUE TITLE
IR instance using Webthings

### ISSUE THREAD

**Issue by RitvikSardana** [WebThingsIO/gateway#2789]
How do I create my own IR remote instance using webthings?
My goal is this - 
IR remote will generate IR codes and I will intercept them using IR receiver which is connected to node MCU, from that I will get the hexCode for each button and then I want to use these hex codes such that I can control the TV using webthings.

**Comment by mrstegeman** [comment]
The easiest thing would be to create a native web thing via the [Web Things Framework](https://webthings.io/framework/).
