### ISSUE TITLE
Ability to change background color

### ISSUE THREAD

**Issue by FCaragay** [WebThingsIO/gateway#2798]
Not sure if this is possible but I would like to be able to customize the background of the entire UI to be a different color besides the light blue it currently is.

**Comment by mrstegeman** [comment]
This could be done through an extension add-on. @flatsiedatsie could probably offer you some good advice on that.

**Comment by flatsiedatsie** [comment]
Have a look at the `Square theme`. It makes a number of superficial changes using CSS and Javascript.
