### ISSUE TITLE
Docker image behind reverse proxy: vapid not configured

### ISSUE THREAD

**Issue by foodev** [WebThingsIO/gateway#2799]
I'm using the official Docker image v1.0.0 and started with a clean setup (deleted any previous Docker volume). I also use nginx as reverse proxy with a setup like this one: https://github.com/WebThingsIO/gateway/issues/1806#issuecomment-739466626

After I started the container and created an account locally (I skipped the subdomain settings) everytime I load the website, I get an error message logged to the console:

![Bildschirmfoto von 2021-03-03 19-42-01](https://user-images.githubusercontent.com/2130727/109855532-af99f180-7c58-11eb-8935-ba546412074f.png)

I guess it never called `/push/register` but I have no idea why or when it should have been called.

**Comment by mrstegeman** [comment]
This is normal. The UI asks the user to enable notifications, and until they do so, this error will be logged.

**Comment by foodev** [comment]
OK, thanks. But the UI did not ask me to enable notifications, yet. When does that happen?

**Comment by mrstegeman** [comment]
It’s browser-specific behavior. You may have that completely disabled in your browser, or it may just be hidden behind a little icon in the address bar.

**Comment by foodev** [comment]
That's weird. I did not disable it in the browser and Firefox does not let me enable notifications for the gateway. For other websites, notifications work fine.
