### ISSUE TITLE
mdns/zeroconf discovery don't working

### ISSUE THREAD

**Issue by stokito** [WebThingsIO/gateway#2823]
I tried to create accessory and discover it via mdns from WOT gateway. From docs it looks like I must add MDNS with txt record `webthing` but in W3C draft said that it should be `wot`. I tried both but the accessory still can be found by webthing gateway.

But from console I can see them:
```
 avahi-browse --all
+ wlp3s0 IPv6 turris                                        _webthing._tcp       local
+ wlp3s0 IPv6 turris                                        _wot._tcp            local
```

Is this implemented in gateway? If yes then how exactly we can do this?

**Comment by benfrancis** [comment]
Hi @stokito,

Yes this is implemented, and as I understand it the implementation currently follows the specification [here](https://webthings.io/api/#mdns-dns-sd) rather than the W3C Working Draft.

> A Web Thing can make itself discoverable on a local network by advertising itself via DNS-SD, with a service type of webthing over TCP, i.e. _webthing._tcp. The service should define a TXT record named path, with its value denoting the URI of the thing description on the Web Thing's web server, e.g. path=/things/lamp. Additionally, a TXT record named tls with a value of 1 should be included if the Web Thing supports connections via HTTPS.

Did you try setting a TXT record named path?

**Comment by stokito** [comment]
Thank you. Yes, I did and I can see it:
```
$ avahi-browse -d local _webthing._tcp --resolve -t 
+ wlp3s0 IPv4 turris                                        _webthing._tcp       local
= wlp3s0 IPv4 turris                                        _webthing._tcp       local
   hostname = [turris.local]
   address = [192.168.1.1]
   port = [80]
   txt = ["path=/nextcloud/things.json"]
```
I using Ubuntu 20.10 and started the gateway from docker with `--network="host"` but still it can't find the webthing accessory.
Anyway, if you said that it must work but it doesn't on my machine then I have to report a bug but I don't want to investigate it.

Also I just tried HomeKit HAP and it also uses MDNS but all basic accessory information is populated via mdns: 
```
	"_hap._tcp": {
		"Kankun_stokito-serv": {
			"txt": "c#=2",
			"txt": "ff=0",
			"txt": "id=6E:40:25:59:53:30",
			"txt": "md=Kankun_SP3",
			"txt": "pv=1.1",
			"txt": "s#=1",
			"txt": "sf=1",
			"txt": "ci=5",
			"port": 9999
		}
	}
```
So name, model, id and category (ci=5 for Light bulb) can't be determined without fetching the json resource. IMHO this is  much simpler and faster. Is any reason why this approach wasn't used in WebThing SD?
