### ISSUE TITLE
Not possible to move a device out of a group if no other devices outside groups

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2862]
STR:
1. Start with no devices
2. Add a device
3. Add a group
4. Drag and drop the device into the group
5. Try to drag the device out of the group

Expected:
* Can move device out of the group so it has no group

Actual:
* Can't move device out of group

CC @bewee

**Comment by bewee** [comment]
Ah, I see, that's true... You could still delete the whole group, that would move all its devices out of it. But it's not elegant. I could try adding a minimum size to the container of ungrouped things, but won't happen before the end of next week.

**Comment by createcandle** [comment]
Possibly related:

- Create one group, add some things
- Marvel at it for a few seconds (really great new feature)
- Drag the group up by its name. See the dotted lines appear
- Release the group

The group has now disappeared from the UI.

The console shows this error:

```
group.js:244 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at e.exports.handleDrop (http://raspberrypi.local:8080/bundle/a3640a0f82e263e36ebe-app.js:8:336335)
```

**Comment by bewee** [comment]
Not related, but definitely a bug that should be fixed!
