### ISSUE TITLE
Thing into group doesn't react on connected_notify()

### ISSUE THREAD

**Issue by retfie** [WebThingsIO/gateway#2870]
When moving thing into group, it doesn't react to connected_notify() call anymore. Moving it back out of group, starts to react again to this call as expected by change its opacity (1/0.5). 

Webthings gateway is checkout at 2ce4a5ab.

**Comment by flatsiedatsie** [comment]
Just noticed this too.

![groups_ignores_connected_state](https://user-images.githubusercontent.com/805405/144246488-cd2df659-51c9-4c24-ae23-287499e97187.gif)
o.
