### ISSUE TITLE
bug: TypeError: rsp.getStatus() is not a function

### ISSUE THREAD

**Issue by jcherrabi** [WebThingsIO/gateway#2878]
Hello there,
i've spent the whole day trying to figure out this error and i can't seem to track why it's happening:
`Error calling API handler: TypeError: rsp.getStatus is not a function`

how to reproduce:
using post man call this API with auth token: for example i will call it against the webhook-events adapter:
`https://mypage.webthings.io/extensions/webhook-events/api/test`

then in your console log you will get the following error:
`Error calling API handler: TypeError: rsp.getStatus is not a function`
`build/controllers/extensions_controller.js:61:33`
so it seems as if api-handler.ts isn't being loaded as that's where the `rsp.getStatus()` call resides and which is a simple wrapper to rsp.status . i've removed .nvm, reinstalled node 12.x directly and still to no avail.

the old version of the `extensions_controller.js` called rsp.status diretly without wrapper and worked as advertised...

can someone please check and let me know if it's a bug or me doing something wrong in my setup.

btw the change happened on commit Migrate to typescript https://github.com/WebThingsIO/gateway-addon-node/commit/ab4ae73f1cc265874913b3d4d55fd34522baa050

Jay

**Comment by jcherrabi** [comment]
here is a screenshot:
btw this happens with any adapter that has a `async handleRequest(request)` implemented.
![image](https://user-images.githubusercontent.com/5914393/134409866-62126d1f-828b-40e0-ba42-7826c693e5ad.png)

**Comment by createcandle** [comment]
I've manually applied the fix and then re-ran `npm start`. The error is gone from the logs. Functionality doesn't seem to be restored though. 

Looking in the logs again I now notice another error. Not sure if it's related though.

`WebSocket sendMessage failed: Error: WebSocket is not open: readyState 3 (CLOSED)`

**Comment by bewee** [comment]
> I've manually applied the fix and then re-ran `npm start`. The error is gone from the logs. Functionality doesn't seem to be restored though.
> 
> Looking in the logs again I now notice another error. Not sure if it's related though.
> 
> `WebSocket sendMessage failed: Error: WebSocket is not open: readyState 3 (CLOSED)`

Just had a look at it again, functionality is indeed restored for me (using the macros addon for testing)

Getting the other error message as well, but independent of this fix.
