### ISSUE TITLE
Matter standard integration

### ISSUE THREAD

**Issue by mhalano** [WebThingsIO/gateway#2890]
A group of companies released, some time ago, a standard to connect smart things inside the house. The standard is called "Matter¨. It would be nice if WebThings support the standard. Here is the link to the project: https://buildwithmatter.com/

**Comment by benfrancis** [comment]
Hi @mhalano,

Thanks for the suggestion. CHIP/Matter support is being tracked here https://github.com/WebThingsIO/addon-list/issues/1037

As far as I know there are not yet any public specifications available to implement.
