### ISSUE TITLE
webthings-gateway-debian-buster-arm64.deb

### ISSUE THREAD

**Issue by dizzwold** [WebThingsIO/gateway#2904]
Will webthings-gateway-debian-buster-arm64.deb, give me buster and webthings on my RPi 4b?
If so how do I unpack it to the sd card?
I'm on a mac running 10.11.6, balena won't open it as the file icon states archive, neither wil winzip of mac, unrarx or unaarchiver?
How do I get this working?

**Comment by benfrancis** [comment]
Hi @dizzwold, .deb files are software packages for use with [Debian's package management system](https://www.debian.org/doc/manuals/debian-reference/ch02.en.html), which you usually install using `apt` or `aptitude`.

If you want to install WebThings Gateway on Debian Buster on a Raspberry Pi 4b, you'll need to [install Debian Buster on the Raspberry Pi](https://wiki.debian.org/RaspberryPi) first, and then [install the .deb package](https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt) using `apt` or another tool.

If you don't have a particular reason for using Debian rather than Raspbian (Raspberry Pi OS) on your Raspberry Pi, then I'd recommend installing the full Raspberry Pi image from the website (https://webthings.io/gateway/) which includes both the OS and the WebThings Gateway software ([instructions here](https://webthings.io/docs/gateway-getting-started-guide.html)).

There is also a [.deb package specifically for Raspbian](https://github.com/WebThingsIO/gateway/releases/download/1.0.0/webthings-gateway-raspbian-buster-armhf.deb) if you want to install it alongside other software on Raspbian.

Does this answer your question?

**Comment by dizzwold** [comment]
Hi Ben,
 Thank you for your reply, detailed information and input.
 What I'm looking at doing, or at least trying to do is to have my RPi running Buster (or alike), along with WebThings while also using a touchscreen.
 I've had webthings running on it's own (headless), but don't like it being headless, I'd rather have a touchscreen. I've also tried the Candle Smart Home System. While Candle is great, you don't seem to be able to do anything else with the RPi, or rather it's above my skill set. Maybe I'm just being greedy and should consider a tablet instead, with a headless RPi running WebThings.
 At least I'm getting some feedback from this thread, unlike the Led Lamp thread. All I want to do is dim my leds.
Thank you again for your time.

Regards,
 Darren.
AKA Dizzwold.

    On Monday, 13 December 2021, 13:21:21 GMT, Ben Francis ***@***.***> wrote:  
 
 


Hi @dizzwold, .deb files are software packages for use with Debian's package management system, which you usually install using apt or aptitude.

If you want to install WebThings Gateway on Debian Buster on a Raspberry Pi 4b, you'll need to install Debian Buster on the Raspberry Pi first, and then install the .deb package using apt or another tool.

If you don't have a particular reason for using Debian rather than Raspbian (Raspberry Pi OS) on your Raspberry Pi, then I'd recommend installing the full Raspberry Pi image from the website (https://webthings.io/gateway/) which includes both the OS and the WebThings Gateway software (instructions here).

There is also a .deb package specifically for Raspbian if you want to install it alongside other software on Raspbian.

Does this answer your question?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benfrancis** [comment]
Closing this as it appears the question is answered, but please feel free to re-open if you have follow-up questions.

**Comment by dizzwold** [comment]
Hi Ben,
 The link (https://webthings.io/gateway/), isn't this just the webthings image I've already used, that is headless?
 I'm looking for a version that I can install on top of Buster, so webthings is working in the background and I can open it when ever.
 Basically using the RPi and touchscreen as a tablet for example.
 Is there an image of webthings available to download onto the RPi after installing buster?
Regards,
 Darren.




    On Tuesday, 14 December 2021, 10:41:54 GMT, Ben Francis ***@***.***> wrote:  
 
 


Closing this as it appears the question is answered, but please feel free to re-open if you have follow-up questions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benfrancis** [comment]
> The link (https://webthings.io/gateway/), isn't this just the webthings image I've already used, that is headless?

Yes.

> I'm looking for a version that I can install on top of Buster, so webthings is working in the background and I can open it when ever.

You can use a .deb package for that, either on Debian Buster or Raspbian Buster. Or install WebThings Gateway manually using the instructions in the [README](https://github.com/WebThingsIO/gateway/blob/master/README.md).

> Is there an image of webthings available to download onto the RPi after installing buster?

Not an image, but a .deb package. You don't have to install Debian to do this, you could also use the full (non-lite) version of Raspbian (now known as [Raspberry Pi OS](https://www.raspberrypi.com/software/)) which includes a desktop environment and is better optimised for the Raspberry Pi.

**Comment by dizzwold** [comment]
Hi Ben,
 Okay I downloaded the webthings-gateway-raspbian-buster-armhf.deb on to my pi already runing Buster, then updated and installed with apt, but then what? How do I open it or register?Sorry.Regards,
 Darren.

    On Wednesday, 15 December 2021, 16:57:34 GMT, Ben Francis ***@***.***> wrote:  
 
 



The link (https://webthings.io/gateway/), isn't this just the webthings image I've already used, that is headless?


Yes.


I'm looking for a version that I can install on top of Buster, so webthings is working in the background and I can open it when ever.


You can use a .deb package for that, either on Debian Buster or Raspbian Buster. Or install WebThings Gateway manually using the instructions in the README.


Is there an image of webthings available to download onto the RPi after installing buster?


Not an image, but a .deb package. You don't have to install Debian to do this, you could also use the full (non-lite) version of Raspbian (now known as Raspberry Pi OS) which includes a desktop environment and is better optimised for the Raspberry Pi.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dizzwold** [comment]
Hi Ben,

 I'm now trying to install webthings on a Pi whith buster already installed.
 I'm now following instructions from the link below;https://github.com/WebThingsIO/gateway
I've installed the dependancies, 
Ubuntu/Debian Linux
Skiped Fedora Linux and Mac OS,
Installed Nod Js by the nvm comand
 When I try to install the 1st command from Setup Bluetooth permissions I get the following;readlink: missing operandTry ‘readlink --help’ for more information.usage: setcap [ -q] [ -v] ( -r| - |<caps>) <filename> [ ... (-r| - |<capsN>) <filenameN> ]
Please could you help?
 Regards,
 Darren.


    On Sunday, 19 December 2021, 18:53:30 GMT, ***@***.*** ***@***.***> wrote:  
 
  Hi Ben,
 Okay I downloaded the webthings-gateway-raspbian-buster-armhf.deb on to my pi already runing Buster, then updated and installed with apt, but then what? How do I open it or register?Sorry.Regards,
 Darren.

    On Wednesday, 15 December 2021, 16:57:34 GMT, Ben Francis ***@***.***> wrote:  
 
 



The link (https://webthings.io/gateway/), isn't this just the webthings image I've already used, that is headless?


Yes.


I'm looking for a version that I can install on top of Buster, so webthings is working in the background and I can open it when ever.


You can use a .deb package for that, either on Debian Buster or Raspbian Buster. Or install WebThings Gateway manually using the instructions in the README.


Is there an image of webthings available to download onto the RPi after installing buster?


Not an image, but a .deb package. You don't have to install Debian to do this, you could also use the full (non-lite) version of Raspbian (now known as Raspberry Pi OS) which includes a desktop environment and is better optimised for the Raspberry Pi.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
