### ISSUE TITLE
Refine Groups UI

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2938]
I'd like to suggest some refinements to the Groups UI before we ship 1.1.

![groups](https://user-images.githubusercontent.com/552417/177819279-566f7a42-60b0-4e26-ae24-8f590249ccb3.png)

Key changes:
1. Add groups via an overflow menu on the add button, rather than via the Add Thing screen. Because a) Adding a group feels like a different action to adding a thing so it feels out of place in the add thing screen and b) Clicking the + button currently does a lot of heavy lifting behind the scenes (like putting all the gateway's radios in pairing mode) which isn't necessary to just add a group
2. Tweaks to the add thing, edit thing and remove thing screens to make them consistent with similar screens
3. A bit of polish on the group UI like updated icons and layout (e.g. full width rather than dynamic width)

(I'm not sure yet about the proposed new thing and group icons)

I've also noticed some bugs with the existing implementation that we need to make sure are fixed before release. I've included a couple of examples of the UI in a broken state, below.

![Screenshot from 2022-07-07 14-45-47](https://user-images.githubusercontent.com/552417/177817970-d99f9599-d57a-4224-9c6c-b44ca90d404e.png)
![Screenshot from 2022-07-07 16-22-49](https://user-images.githubusercontent.com/552417/177817976-5cdcfa72-5e95-4771-a3fb-ce4ce4d2081f.png)

Hopefully they can be fixed at the same time.

CC @bewee

**Comment by bewee** [comment]
Hi guys,
Sorry for ignoring this for so long! I hoped to find time earlier, but was on vacation, then had to hand in my thesis, and am now quite busy with moving. Will try to have a look at this ASAP (it's all marked as unread in my mails) but can't guarantee until when I will ultimately get to do something.

**Comment by benfrancis** [comment]
Hi @bewee, no worries, good luck with the move!

I wasn't necessarily expecting you to do the implementation, but it would be good to get your feedback on the design.

If you can find the time to implement the changes that would be great! But if not I will try to find time to do it.

I'd really like to get this feature polished and get a 1.1 release out :)

**Comment by bewee** [comment]
Most critical fixes in #2990. I could swear that scrolling worked properly back in January when I last worked on this feature, but I am no longer able to execute the commit from back then. Whatsoever... Maybe just something changed about the outer containers :shrug: 
The new mockup looks quite good to me! Will have a look at moving the add group menu later today or within the following week. Could you either provide me with the new thing and group icons or just add them in on your own? Thanks :)

**Comment by benfrancis** [comment]
I've been working on refining the UI design a little prior to implementation:

![groups2](https://github.com/WebThingsIO/gateway/assets/552417/0339766c-b9ef-481e-b815-7b0a7b10b4e9)

SVG icons:
- [add-thing.svg](https://drive.google.com/file/d/1_l24D_Sb5JvmWKjPKLJ3JvdvySW4aN7F/view?usp=sharing)
- [add-group.svg](https://drive.google.com/file/d/16nVEunlCsdjqADhgE6El8lUO-3KhM0vg/view?usp=sharing)
- [group.svg](https://drive.google.com/file/d/1qtPos9GNxO9HufD4UUUmnOAr8ZmiM0FE/view?usp=sharing)
- [up-arrow.svg](https://drive.google.com/file/d/1J3C2D9x_kwV1QQoAq8T1NbozXJ44OsgM/view?usp=sharing)
- [down-arrow.svg](https://drive.google.com/file/d/1rKr_-HTJIkKzggY8lG9RxAHwRCcDJP_g/view?usp=sharing)
