### ISSUE TITLE
webthingsio and Pi OS

### ISSUE THREAD

**Issue by jaychub** [WebThingsIO/gateway#2946]
Hello,
does anyone know if there is an image with the latest PI OS and webthings?

reason i ask is because i have a pi 2 B and installing everything from scratch kills the pi.

cheers,
Jay

**Comment by benfrancis** [comment]
Not yet I'm afraid. If you want a more up to date OS you could try flashing the old WebThings Gateway and then upgrading the OS yourself, but I'm not sure if you'll have any more success with that.

**Comment by jaychub** [comment]
Hello benfrancis,
thank you for the quick reply, i'm trying to install it right now, i have a question will nodejs version 14.20.0 run OK or do i have to use 14.14.31?

so far running npm ci gets stuck in sqlite3 with warning like the below, is that ok? should i wait until it finishes?
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c: In function ‘cellArea’:
Release/obj/gen/sqlite-autoconf-3340000/sqlite3.c:190977:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
190977 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cheers,
Jay

**Comment by kgiori** [comment]
Jay,

You might also try the Candle build (forked from Web Things 1.1 I think) which is specific to RPi platforms:
https://www.candlesmarthome.com/

kathy

**Comment by jaychub** [comment]
I actually ended up going back to mozilla-iot version 0.12, and it works great :)
ever since you guys switched to TypeScript things got out of hand...
i will continue to use V0.12 for now and it works with all of the Addons that were build for it.

Cheers,
Jay

**Comment by benfrancis** [comment]
> I actually ended up going back to mozilla-iot version 0.12, and it works great :)

I wouldn't recommend using version 0.12 because a lot of the back end services it relies on have been switched off by Mozilla and you won't receive any future updates.

> ever since you guys switched to TypeScript things got out of hand...

Can you be more specific about what problems you're seeing with TypeScript? Is it problems with building on the Raspberry Pi that you're referring to? Note that the WebThings Gateway 1.0 was before the TypeScript migration.
