### ISSUE TITLE
Can not build with the node version shown in the README

### ISSUE THREAD

**Issue by jaychub** [WebThingsIO/gateway#2947]
Hello guys,
i have a pi 3 B+ and installed PI OS lite 32bit and followed the instrcution to install the gateway but it failed when i get to npm start, the failure starts while installing sqlite3 from source as no prebuild package exists and ended up with a javascript out of memory issue..

what am i doing wrong please?
the reason why i can't use the prebuilt image is i need the latest fixes from github...

anyone care to try this and update the instructions please?

thanks,
Jay

**Comment by jaychub** [comment]
after 6 hours of messing with the installation i finally got to work and someone has to update the read me file as that's where the issue is because it is miss leading..

the node version that must be used to build the gateway is node 10 and not node 12 as indicated in the readme... when using node 12 it leads to a js trace memory error and never builds. so when i reverted back to node 10 and ran npm start it finally build and started.

after that i'm able to switch back to node 12 and start the gateway using npm run run-only.

so to the maintainers either update the build to use node 12 or fix the readme to now node10 and not node v12.19.0

cheers,
Jay

**Comment by benfrancis** [comment]
Hi @jaychub, thanks for reporting this and for persevering to figure out what was wrong.

I'm afraid I'm not as familiar with the build process as I would like, and the person who wrote it has moved on.

The README just says to install "an LTS version of node", but the fact that the examples show v12.x does suggest that it worked for someone at some point.

It appears that @dyap2 bumped the version number in https://github.com/WebThingsIO/gateway/pull/2601

@dyap2 can you conform whether you have tested building with node v12.x?

@jaychub If possible can you please share the error message you saw to see if we can reproduce the same error?

Thanks
