### ISSUE TITLE
Unable to register or re-claim subdomains

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2948]
STR:
* Try to register or re-claim a subdomain during first time setup

Expected:
* Registration successful

Actual:
* Error displayed: "Error issuing certificate. Please try again."

Error log:
```
2022-09-20 12:50:18.354 INFO   : Starting registration
2022-09-20 12:50:19.210 INFO   : Sent subscription to registration server
2022-09-20 12:50:23.278 INFO   : Set DNS token on registration server
2022-09-20 12:50:34.182 ERROR  : Failed to generate certificate: Error: Error finalizing order :: signature algorithm not supported
    at AcmeApi.apiRequest (/home/tola/Code/benfrancis/gateway/node_modules/acme-client/src/api.js:54:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async AcmeClient.finalizeOrder (/home/tola/Code/benfrancis/gateway/node_modules/acme-client/src/client.js:349:22)
    at async module.exports (/home/tola/Code/benfrancis/gateway/node_modules/acme-client/src/auto.js:149:5)
    at async Object.register (/home/tola/Code/benfrancis/gateway/build/certificate-manager.js:171:22)
    at async /home/tola/Code/benfrancis/gateway/build/controllers/settings_controller.js:139:9

```

First reported in https://discourse.mozilla.org/t/error-issuing-certificate/105596

From my investigation so far it appears that as of 15th September 2022, Let's Encrypt [stopped supporting](https://community.letsencrypt.org/t/rejecting-sha-1-csrs-and-validation-using-tls-1-0-1-1-urls/175144) certificate signing requests using the SHA-1 hash algorithm used by the version of the [acme-client](https://www.npmjs.com/package/acme-client) npm package used by WebThings Gateway (4.1.3).

Hopefully this can be solved by just upgrading the acme-client package to version 4.2.4 or above.

We're probably going to want to put out a bugfix release to fix this as a matter of urgency, since it breaks all subdomain registrations and reclaims.

**Comment by benfrancis** [comment]
I have a fix available in https://github.com/WebThingsIO/gateway/pull/2949

We just need to figure out the best strategy to get this fix out to people (i.e. in what release).

**Comment by EricLEdberg** [comment]
Is it possible to update the docker image at:      https://hub.docker.com/r/webthingsio/gateway
It's not been update for a couple years.
Wish I new the procedures to build a working image.  I've tried twice using the instructions and failed each time :-(

**Comment by benfrancis** [comment]
Hi @EricLEdberg, yes my intention is to update all of the packages and image formats at the same time when pushing out a release. In theory that should be mostly automated, but let's see how it goes.

**Comment by MajesticFalcon** [comment]
Are we close to having a release with the changes merged in? I had an issue where I needed to reflash and now I am SOL

**Comment by benfrancis** [comment]
Hi @MajesticFalcon, sorry for the inconvenience.

The fix has now landed on the v1.0.X and master branches, along with some security patches, having being code reviewed over the weekend. It's ready to use if you want to build yourself.

My aim is to generate a 1.0.1-pre1 pre-release build within the next three days, which will then need testing before the release is pushed out to all gateways via an OTA update.

Please bear with us as we rely on volunteer contributions to get this out. I will share details of the pre-release on this issue when it's available for anyone who wants to help with testing.

**Comment by jekkel** [comment]
@benfrancis Sorry for bothering - I'd be willing to help now that another 6 weeks passed and I can't access the gateway securely anymore. Is there any switch to allow the gateway to install pre-releases?

**Comment by wfahle** [comment]
@jekkel you can build it yourself: https://github.com/WebThingsIO/gateway The fix is in the master branch now.

**Comment by Hipnagogi** [comment]
Hi is there any info about this issue?

**Comment by benfrancis** [comment]
@Hipnagogi Yes, good news. It was fixed in the 1.1 release which was announced yesterday https://discourse.mozilla.org/t/announcing-webthings-gateway-1-1/109643

**Comment by Hipnagogi** [comment]
That's a great news. I have my webthings updated. How can I reclaim my old domain or generate certificate for the new domain? BTW is there any option to change the domain after instalation and configuration of the webthings?

**Comment by EricLEdberg** [comment]
@Hipnagogi -  I found this forum procedure.  I've not tried it...

![image](https://user-images.githubusercontent.com/8417082/211014761-2aab670b-03d7-4b66-84ff-6eeb4163e85d.png)

at:

https://discourse.mozilla.org/t/ssl-error-and-reclaim-domain-procedure-not-working/52890

**Comment by benfrancis** [comment]
You can currently only register or re-claim a domain during first time setup of the gateway.

If your gateway is already configured to use a domain then it should automatically renew the certificate and the remote access service should just start working again.

**Comment by benfrancis** [comment]
@EricLEdberg  wrote:
> I found this forum procedure. I've not tried it...

That might work as a way to force the gateway to do domain setup again (I've never tried it), but note that those instructions are old and I believe the `mozilla-iot-gateway` service is now called `webthings-gateway`.

Manually deleting records from the database is generally a risky approach...

**Comment by benfrancis** [comment]
@Hipnagogi If you successfully registered a new webthings.io subdomain about a week ago (which would only have been possible using a 1.1 alpha or beta release, is that what you were using?) then the certificate should not have expired yet and if you're getting a certificate error then it may have another cause (e.g. the gateway being unreachable).

Have you tried rebooting the gateway?

If that doesn't work and you are able to do a fresh install of 1.1 then you should be able to re-claim your domain during first time setup.

Otherwise we will need more information to help you diagnose the problem, such as error messages from logs (Settings -> Developer -> View Internal Logs).

Please let me know if I've misunderstood your problem.

**Comment by Hipnagogi** [comment]
Hi - I have registered about week ago on version 1.0.
After update the certificate was still unissued for the new domain (created 30.12.2022)

I create new fresh instalation of gateway in version 1.1 and successfully reclaim my old domain  created in the middle of 2022. 
Thanks for help :)
