### ISSUE TITLE
Need to change gateway-addon-python version in requirements.txt

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2979]
The build scripts for the .deb and .rpm packages are currently [failing](https://github.com/WebThingsIO/gateway/actions/runs/3183322964/jobs/5190401290) due to not recognising the format of the version number of the gateway-addon-python package in https://github.com/WebThingsIO/gateway/blob/master/requirements.txt

`error: pathspec 'v1.0.1' did not match any file(s) known to git`

The script at:

https://github.com/WebThingsIO/gateway/blob/master/deb/generate-tarball.sh#L6

Is not recognising the `-alpha` in `1.0.1-alpha`

It either needs to be reverted to `v1.0.0`, or we need to tag a 1.0.1 version without the `-alpha` suffix.

**Comment by benfrancis** [comment]
@tim-hellhake I note that you made the change from `v1.0.0` to `1.0.1-alpha.1` in https://github.com/WebThingsIO/gateway/commit/772e98b80b819be6a44db184adf274a9a97c1b42

Do you think we should take `v1.0.0` or rename `1.0.1-alpha.1`?

**Comment by tim-hellhake** [comment]
I added the `1.0.1` tag.
I think is the best option since it will be shipped with the 1.0.1 version of the gateway.

**Comment by benfrancis** [comment]
@tim-hellhake Thank you.

Before I submit a new PR to change requirements.txt, is there a reason you changed the naming convention from v1.0.1 to 1.0.1? I think this will break the build script at this line https://github.com/WebThingsIO/gateway/blob/master/deb/generate-tarball.sh#L21

**Comment by tim-hellhake** [comment]
Not really.
I just merely removed the postfix.
I'll push a new tag.

**Comment by tim-hellhake** [comment]
It's `v1.0.1` now
