### ISSUE TITLE
Raspbian image build error: `unable to set CAP_SETFCAP effective capability: Operation not permitted`

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2985]
STR:
- Checkout the v1.0.X branch once https://github.com/WebThingsIO/gateway/pull/2978 lands (in the meantime you can use this branch https://github.com/benfrancis/gateway/tree/buster-build)
- Follow the instructions on the wiki to build the Raspbian image https://github.com/WebThingsIO/wiki/wiki/#the-new-way

Expected:
- Successful build

Actual:

```
+ setcap cap_net_raw+eip /usr/bin/python3.7
unable to set CAP_SETFCAP effective capability: Operation not permitted
```

This appears to be triggered by this line in our build process https://github.com/WebThingsIO/gateway/blob/master/image/stage3/01-install-deps/01-run-chroot.sh#L6

Adding sudo to the front does not appear to help:

```
+ sudo setcap cap_net_raw+eip /usr/bin/python3.7
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown QEMU_IFLA_INFO_KIND ip6tnl
Unknown host QEMU_IFLA type: 54
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
sudo: unable to resolve host d6427c145247: Name or service not known
unable to set CAP_SETFCAP effective capability: Operation not permitted
```

This build error is blocking the criticial 1.0.1 release.

**Comment by benfrancis** [comment]
I've noticed that if I comment out the line for Python, the line later on the script which does the same for node generates the same error. This seems to suggest something has changed in the distribution which is preventing setcap from working.

```
+ sudo setcap cap_net_raw+eip /home/pi/.nvm/versions/node/v10.24.1/bin/node
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
Unknown QEMU_IFLA_INFO_KIND ip6tnl
Unknown host QEMU_IFLA type: 54
Unknown host QEMU_IFLA type: 50
Unknown host QEMU_IFLA type: 51
sudo: unable to resolve host 6afa45a19831: Name or service not known
unable to set CAP_SETFCAP effective capability: Operation not permitted
```

**Comment by tim-hellhake** [comment]
Yeah, that's what I anticipated.
I already suspected the `setcap` binary or some security mechanism to be the problem.

**Comment by benfrancis** [comment]
We may need to tell Docker about capabilities.

To test this theory we could add `--cap-add=ALL` to the docker run command in the build process, but I think that may happen inside pi-gen. If that works we can narrow it down the specific capabilities needed for Bluetooth.

**Comment by benfrancis** [comment]
Actually I think pi-gen may already do this https://github.com/RPi-Distro/pi-gen/blob/master/build-docker.sh#L109 - so that isn't it.

**Comment by benfrancis** [comment]
@davehylands has identified a possible cause in pi-gen, which appears to [drop capabilities](https://github.com/RPi-Distro/pi-gen/blob/master/scripts/common#L93) from the chroot environment.

I've filed an [issue](https://github.com/RPi-Distro/pi-gen/issues/643) upstream to ask for advice.

Dave has also suggested a potential workaround, although to be honest I'm not exactly sure where to start with this approach (which may be beyond my shell scripting skills!)

> I don’t think that there is anyway to get back the capability once it’s been dropped, so you won’t be able to do anything from within that particular script.
> 
> You should be able to do it from one of the other scripts but you’d need to use a different path since you won’t be in the chroot environment.
> 
> Maybe have the chroot script figure out the paths while inside the root and write the paths into a file and then have a later step add the appropriate prefix and do the setcap calls.

**Comment by benfrancis** [comment]
There is now an upstream [fix](https://github.com/RPi-Distro/pi-gen/commit/c3083ecd503629eac5184ec692f65bbbd28ac317) for this issue in the form of a `SETFCAP` build option for pi-gen which allows capabilities to be set inside chroot.

Unfortunately that fix is only currently available on the master branch and we need it on buster.

For now I have forked pi-gen and manually removed the `--drop=cap_setfcap` argument from their build script so that we are able to set capabilities.

If they backport the new build option to the buster branch then we can later switch back to using the upstream repo directly (see https://github.com/RPi-Distro/pi-gen/issues/643).

https://github.com/WebThingsIO/gateway/pull/2999 should therefore fix this issue.

**Comment by benfrancis** [comment]
Fixed by https://github.com/WebThingsIO/gateway/pull/2999 on v1.0.X and https://github.com/WebThingsIO/gateway/pull/3003 on master
