### ISSUE TITLE
Create a workflow for pre-release tags

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#2987]
This is a follow-up to #2980 in which we discovered that tagging a release automatically publishes a new image to DockerHub.

Currently when a new tag is created on the repo which looks like a semver version tag, a GitHub [workflow](https://github.com/WebThingsIO/gateway/blob/master/.github/workflows/release.yml) creates a new release and tries to build a Raspberry Pi image, apt and rpm packages, and a docker image.

The release is initially set as a pre-release on GitHub and production gateways will not pull down an OTA update until the pre-release flag is removed. However, the current release workflow will automatically try to publish the docker image to DockerHub, even if the pre-release flag is set. This may result in an un-tested image being pushed to DockerHub.

As far as I can tell it isn't possible to create a workflow which only pushes an image to DockerHub when the pre-release flag is removed, but what we could do is set up a separate workflow which is triggered when a tag ending in "-pre" is added. This workflow could do everything the current release workflow does, but without publishing anything to DockerHub.

**Comment by benfrancis** [comment]
Not exactly sure what to do about this:
- If the docker builds don't get uploaded to DockerHub, where should they go
- Creating a new workflow called "prerelease" is probably a bit confusing because we probably want the "release" worflow to initially set the release as "prerelease" as well, and only manually untick it when we want the update pushed out to gateways

**Comment by benfrancis** [comment]
> * If the docker builds don't get uploaded to DockerHub, where should they go?

Would it make sense for a pre-release to push a build to DockerHub using the "latest" tag, but not a versioned tag?

**Comment by tim-hellhake** [comment]
> Would it make sense for a pre-release to push a build to DockerHub using the "latest" tag, but not a versioned tag?

I wouldn't use `latest` for this.
A lot of people pull the image by its name expecting to get the latest stable version.
I would instead use a special tag like `prerelease`.

**Comment by tim-hellhake** [comment]
I think the root problem here is that the final release step takes place outside the ci system.
Semantic versioning explicitly supports prereleases using a postfix.
In my opinion, the proper way would be to have separate workflows.

**Comment by benfrancis** [comment]
@tim-hellhake Hmm, I created a tag called 1.0.1-alpha.1, and it doesn't appear to have triggered the workflow. Any ideas?
