### ISSUE TITLE
Certificate expired for webthings.io tunnel

### ISSUE THREAD

**Issue by Utopiah** [WebThingsIO/gateway#3027]
Hi, I tried to access utopiah.webthings.io but the certificate expired few months ago. I don't remember modifying anything myself there so I imagine it was automated but somehow isn't anymore.

Anything I could do to force a manual renewal?

**Comment by benfrancis** [comment]
You can either manually upgrade the acme-client npm module, or wait for the 1.1 update which should be coming soon.

See https://github.com/WebThingsIO/gateway/pull/2949 for the fix.

Sorry for any inconvenience.

Closing as duplicate of https://github.com/WebThingsIO/gateway/issues/2948
