### ISSUE TITLE
Re-enable but deprecate `visible` member of properties

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#3038]
Shortly after the 1.0 release, support for invisible properties (`visible: false`) of Things was removed from
- [gateway](https://github.com/WebThingsIO/gateway/pull/2672)
- [gateway-addon-node](https://github.com/WebThingsIO/gateway-addon-node/pull/82)
- [gateway-addon-python](https://github.com/WebThingsIO/gateway-addon-python/pull/87)
- [gateway-addon-ipc-schema](https://github.com/WebThingsIO/gateway-addon-ipc-schema/pull/15)

In the 1.1.0-alpha.2 release this has resulted in the Zigbee, Z-Wave, HomeKit, Tuya add-ons (which still use this feature) being broken, as well as an unknown number of other add-ons.

A [fix](https://github.com/bewee/tuya-adapter/pull/48) has landed for the Tuya adapter and there's an [untested fix](https://github.com/WebThingsIO/homekit-adapter/pull/63) for the HomeKit adapter, but we don't know how many other add-ons might be affected.

Rather than making this breaking change in the 1.1 release and requiring a fix in all add-ons which use it, another option is to revert the changes at the gateway level in order to continue to support this feature, but print a deprecation warning on the console every time it's used. Then we can remove the feature entirely in a future release.

Apart from being a lot of work, my other concern with this approach is that there was a reported [bug](https://github.com/WebThingsIO/gateway/issues/2670) with this feature in 1.0 in which invisible properties were always shown to users even if set as not visible. I'm not sure what the UX impact is of this for add-ons which heavily use the feature, and whether that would need to be fixed or whether we leave it that way in order to encourage add-on developers to stop using the feature. Presumably whatever the effect is it has been the case for the past two years so users will already have noticed.

See also: https://github.com/WebThingsIO/gateway/issues/2670, https://github.com/WebThingsIO/homekit-adapter/issues/62

The steps I think will be necessary to fix this at the gateway level:
- [x] Fix gateway-addon-ipc-schema (https://github.com/WebThingsIO/gateway-addon-ipc-schema/pull/24)
  - [x] Revert commit
  - [x] Mark visible member as deprecated
  - [x] Tag a new version
- [x] Fix gateway-addon-node (https://github.com/WebThingsIO/gateway-addon-node/pull/119)
  - [x] Revert commit
  - [x] Bump schema submodule
  - [x] Tag and release new version
- [x] Fix gateway-addon-python (https://github.com/WebThingsIO/gateway-addon-python/pull/92)
  - [x] Revert commit
  - [x] Bump schema submodule
  - [x] Tag and release new version
- [x] Fix gateway (https://github.com/WebThingsIO/gateway/pull/3042)
  - [ ] ~~Revert commit~~
  - [x] Bump gateway-addon-node version
  - [x] Bump gateway-addon-python version
  - [x] Bump gateway version
  - [x] Tag and release new version

**Comment by freaktechnik** [comment]
Just to make sure we're not reverting too much, as far as I'm aware gateway 1.0 already ignored the actual value of `visible` and add-ons had to remove invisible properties themselves. It's just the gateway-addon-node/gateway-addon-python that changed behavior.

**Comment by benfrancis** [comment]
@freaktechnik That does seem to be the case from https://github.com/WebThingsIO/gateway/issues/2670 yes, though I think at the time it was considered more of a bug than a feature.

I'm not sure whether or not we should revert https://github.com/WebThingsIO/gateway/pull/2672, but it may have no effect.
