### ISSUE TITLE
Unable to add any new Things in 1.1 beta

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#3046]
STR:
- Upgrade to 1.1.0-beta.1
- Install Virtual Things adapter add-on and DateTime adapter add-on
- Click "+" on the things screen

Expected:
- New devices appear

Actual:
- No devices appear

**Comment by benfrancis** [comment]
This is reproduceable for me on master as well, which may be a clue.

I suspect a regression in gateway-addon-node or gateway-addon-ipc-schema.

**Comment by benfrancis** [comment]
The regression actually appears to be caused by https://github.com/WebThingsIO/gateway/commit/1cd6034b751621150a8dc50e6908e9b46412ccc2

Also reproduceable on master which also has that patch.

**Comment by GHoGit** [comment]
Had blank page + several other rendering issues this morning. 1.0 a.1.A.
Removed all unused add-ons etc.
Problem most likely was Firefox 108. Test duckduckgo and Chrome, both OK,
'Downgraded FF to 1.07 -> OK

Regards
GHoGit
