### ISSUE TITLE
Attempt OTA from 1.1.0alpha.2 to 1.1.0.beta.2. Observe no change.

### ISSUE THREAD

**Issue by GHoGit** [WebThingsIO/gateway#3054]
Attempt at OTA as per https://github.com/WebThingsIO/wiki/wiki/Testing-prerelease-OTA-updates.

~/webthings/gateway/config:

 updates: {
    // URL of update server
    url: 'https://api.webthings.io:8443/releases',

    // Whether or not to allow prerelease updates
    allowPrerelease: true,
  },

After reboot I see no change.

... pasted screen shot lost ..
Shows 1.1.0.alpha.2

Downloaded image, flashing next.

Regards
GHo

**Comment by benfrancis** [comment]
Thanks for reporting.

What was the screenshot?

What happens when you go to Settings -> Updates?

Does it say "Your system is up to date" or does it provide a button to manually upgrade?

**Comment by GHoGit** [comment]
Your system is up to date.
Current version 1.1.0-alpha.2
Last update: Never
Enable automatic updates -> checked

Update button in top of screen is active and results in no apparent change.

Have not inspected the flash and logs there, maybe the version label is not updated 8-)

Regards
GHo

**Comment by benfrancis** [comment]
The update button shouldn't be visible if no update is available. A screenshot would actually be helpful.

It is possible that the updates list is being cached somewhere, but I'm not able to reproduce that.

**Comment by GHoGit** [comment]
![image](https://user-images.githubusercontent.com/120657521/208163448-ff65148d-64d5-4f6b-a066-2849d40ecb24.png)

I have kept the flash, so I can pop it back in, and make other screen-shot or inspect log.
Possibly, another boot may remedy stuff.

Flashed another fresh Sandisk with b.2 and booted into the registration screen.
Entered same domain name as for alpha. Selected 'reclaim', but still waiting for mail.
Was the trick here to choose 'skip' ?

**Comment by GHoGit** [comment]
Things tend to sort themselves out in the end ...
This is what I see this morning:
![image](https://user-images.githubusercontent.com/120657521/208231740-0f36563e-a800-43a2-baa2-f88c2a55bf9d.png)

Also for some reason, square theme was enabled in the process.

**Comment by justdave** [comment]
Fwiw, when I tried to update from alpha 1 to beta 2 yesterday, it showed the update available but didn't give me a way to run it. I didn't think to grab a screen shot. I ended up running the update check script from the command line, which successfully ran the upgrade. I suspect it does do it automatically overnight and that's probably how yours worked.

**Comment by GHoGit** [comment]
Yes, I too guessed that some 'nightly' job had taken care of things.
Then, automatic update works, but possibly not on demand from UI.

Otherwise, for me both a2 running for a full week or so and  b2 a couple of days, behave well.

The square theme seems to activate on first reboot after toggling, so I must have it the button some time earlier that evening..

**Comment by benfrancis** [comment]
Generally I recommend waiting for automatic upgrades. Manual upgrades do work, but the upgrade process takes a long time and people often assume something has broken.

The square theme wasn't working in 1.1.0-beta.1 but is working in 1.1.0-beta.2. It was probably enabled but not working before the upgrade.

Please re-open if you find reproduceable steps for manual upgrades not working.
