### ISSUE TITLE
start4.elf: is not compatible   Raspberry Pi 4 Model B - 4GB

### ISSUE THREAD

**Issue by DustyFlowerPot** [WebThingsIO/gateway#3059]
Hi there

Im very new to the Raspberry pi world so bare with me.  

Pi os is booting up fine, however when I try to boot up Picroft im getting this screen everytime.  

Ive tried updating bootloader via imager and raspi configure.

Could anyone explain what i need to do?

kind regards

Michael  
![PXL_20230104_121112261](https://user-images.githubusercontent.com/121657892/210553970-4a972e0f-4c14-4378-a073-6fd4d8895112.jpeg)

**Comment by benfrancis** [comment]
Did you mean to file this under https://github.com/MycroftAI?

Please reopen if you have a question about WebThings Gateway.
