### ISSUE TITLE
Error on startup with docker-compose

### ISSUE THREAD

**Issue by rstp** [WebThingsIO/gateway#3114]
Please help as I have tried the latest docker image and a local image build using the cloned directory and I always get the following error on startup:

webthings-gateway  | + mkdir -p /home/node/.webthings/config
webthings-gateway  | + ./tools/update-addons.sh
webthings-gateway  | internal/modules/cjs/loader.js:1057
webthings-gateway  |   return process.dlopen(module, path.toNamespacedPath(filename));
webthings-gateway  |                  ^
webthings-gateway  | 
webthings-gateway  | Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/node/webthings/gateway/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
webthings-gateway  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
webthings-gateway  |     at Module.load (internal/modules/cjs/loader.js:863:32)
webthings-gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
webthings-gateway  |     at Module.require (internal/modules/cjs/loader.js:887:19)
webthings-gateway  |     at require (internal/modules/cjs/helpers.js:74:18)
webthings-gateway  |     at Object.<anonymous> (/home/node/webthings/gateway/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
webthings-gateway  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
webthings-gateway  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
webthings-gateway  |     at Module.load (internal/modules/cjs/loader.js:863:32)
webthings-gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
webthings-gateway exited with code 1

I have tried on two different linuses Debian Buster and Ubuntu 22.04 with the same results.
Thanks.
Robert

**Comment by benfrancis** [comment]
@rstp Thank you for reporting this. I'm aware there are problems with the docker image, but this error is potentially different to the other widely encountered error https://github.com/WebThingsIO/gateway/issues/3043

Could you please provide some more detailed steps to reproduce this error so that people can try to debug it?

Thank you

**Comment by rstp** [comment]
I'm sorry i have made so many attempts at building, configuring, docker-compose, docker stack deploy that I cannot reproduce.  HOWEVER everytime i try now i get the same error as in #3043.

Will you please close this here issue #3114 for now.
