### ISSUE TITLE
[Snap] Implement Network Settings

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/gateway#3155]
_As a user I want to be able to configure my network settings when using the snap package so that I can connect my gateway to a network._

Currently clicking on Network Settings in the web interface when using the snap package on Ubuntu displays a message which says "Network settings are not supported for this platform." This is because network settings are not implemented for Ubuntu, or Ubuntu Core.

This will require implementing network settings using NetworkManager in linux-ubuntu.ts and/or creating a linux-ubuntu-core.ts in [/src/platforms](https://github.com/WebThingsIO/gateway/tree/master/src/platforms).

See https://github.com/krellian/kiosk/blob/master/services/models/network.js for inspiration.

This will likely also require the snap to be permitted to use an additional [interface](https://snapcraft.io/docs/supported-interfaces).

**Comment by benfrancis** [comment]
@ogra1 The way I have been planning to implement this is to request the [`network-manager`](https://ubuntu.com/core/docs/networkmanager) interface and configure networking by communicating with NetworkManager over D-Bus from Node.js. I previously [did something similar](https://github.com/krellian/kiosk/blob/master/services/models/network.js) for Krellian Kiosk, but it's quite low level and fiddly to implement and I found the documentation of the NetworkManager D-Bus API quite difficult to understand.

I note that there appear to be multiple [interfaces](https://snapcraft.io/docs/supported-interfaces) for modifying network settings so before I make a start on this, is there a simpler approach I should be considering?

The [WebThings Gateway user manual](https://webthings.io/docs/gateway/settings/#network) should give you an idea of the kinds of settings which need to be modified from Node.js.

There are other settings that will need implementing later including configuring [mDNS](https://github.com/WebThingsIO/gateway/issues/3157), and a [Wi-Fi hotspot](https://github.com/WebThingsIO/gateway/issues/3156) during first time setup.

**Comment by benfrancis** [comment]
Potential approaches to implementing networking on Ubuntu Core:

- [network-setup-control](https://snapcraft.io/docs/network-setup-control-interface)  interface
	- "allows read/write access to Netplan configuration files" - probably not enough for what we need. We need to be able to list network interfaces and scan for Wi-Fi networks etc.
- [network-control interface](https://snapcraft.io/docs/network-control-interface)
	- "enables the configuration of networking and network namespaces via `ip netns`, providing a wide, privileged access to networking" - I don't know a lot about this
-  [network-manager](https://snapcraft.io/docs/network-manager-interface) interface
	- "enables access to [NetworkManager](https://docs.ubuntu.com/core/en/stacks/network/network-manager/docs/), providing privileged access to configure and observe networking." - Does this just mean via DBus, or also the nmcli command line interface?
	- [dbus](https://www.npmjs.com/package/dbus) npm module to provide raw access to dbus, I've used this before but it's tricky to use and the npm module hasn't been updated for 5 years
		- E.g. https://github.com/krellian/kiosk/blob/master/services/models/network.js
	- [network-manager](https://www.npmjs.com/package/node-network-manager) npm module to control NetworkManager
		- Appears to call nmcli on the back end https://github.com/MahdadGhasemian/node-network-manager/blob/main/index.js

**Comment by dilyn-corner** [comment]
> "enables access to [NetworkManager](https://docs.ubuntu.com/core/en/stacks/network/network-manager/docs/), providing privileged access to configure and observe networking." - Does this just mean via DBus, or also the nmcli command line interface?

If you include `nmcli` in the snap, you should be able to use it. You can see what the [network-manager](https://github.com/canonical/network-manager-snap/tree/snap-22) snap does to accomplish its tasks in this matter.

**Comment by benfrancis** [comment]
@dilyn-corner wrote:
> If you include nmcli in the snap, you should be able to use it. You can see what the [network-manager](https://github.com/canonical/network-manager-snap/tree/snap-22) snap does to accomplish its tasks in this matter.

Hah, it would have been useful to know that ~1,000 lines of code ago! But by the looks of it that requires building nmcli from source inside my snap, which seems a bit excessive. And my assumption was that the DBus API would be more stable than the command line interface. So possibly simpler from the application code point of view, but definitely more complicated from a multi-architecture build point of view.

Having spent most of the last couple of weeks implementing network settings for the gateway using the DBus API I guess I'm kind of committed to that route now, so I'll have to see how it goes.

**Comment by dilyn-corner** [comment]
😅 I do agree that the dbus API is probably more stable and it is usually the way I'd recommend going.

**Comment by benfrancis** [comment]
@dilyn-corner / @ogra1 I'm seeing something odd I can't explain.

I'm [setting](https://github.com/WebThingsIO/gateway/blob/abde760d03f0f1fe29b1d9408d20c3a5c2144508/src/platforms/linux-ubuntu.ts#L205) a static IP address (and subnet and gateway) via the NetworkManager D-Bus API on Ubuntu Desktop, using [`org.freedesktop.NetworkManager.Settings.Connection.Update()`](https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html#gdbus-method-org-freedesktop-NetworkManager-Settings-Connection.Update). It appears to save the settings successfully and when I view network settings in the Ubuntu Settings UI or with `nmcli` it shows the new settings. However, if I then check my current IP address using `ip a` or `hostname -I` I see the old IP address.

What am I missing?

**Comment by benfrancis** [comment]
Huh, it appears that `Update()` does not actually update the settings, you have to call `Reapply()` on the Device object or re-active the connection in order for the changes to take effect...
