### ISSUE TITLE
Implement a release creation/version bumping script

### ISSUE THREAD

**Issue by hobinjk** [WebThingsIO/gateway#326]
We could make releases easier by creating a script that given a desired version updates package.json and creates a branch/release. This would be useful especially if we want to do weekly releases and if we could roll it into an all-in-one script with `create-release-archives.sh`

**Comment by mrstegeman** [comment]
https://github.com/WebThingsIO/wiki/wiki/How-To-Release-a-Gateway-OTA-Update
