### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by apiel** [WebThingsIO/gateway#631]
Hi,
Would be great that you include swagger for the API definition, it would then be easier for everybody to understand your entry points.

Thx for your work ;-)

**Comment by dhylands** [comment]
Which API definition are you referring to?

**Comment by apiel** [comment]
You have multiple entry point to the gateway, would be great to reference them, for this use-case there is a common way is to use swagger.

ThingsController.get('/:thingId'
ThingsController.get('/:thingId/properties/:propertyName'
ThingsController.put('/:thingId/properties/:propertyName'
CommandsController.post('/'
ActionsController.get('/:actionId'
....

**Comment by Swaagie** [comment]
I would argue those routes are mostly internal to the web interface. I don't see the value in adding swagger definitions to routes that are not part of a public API. It would allow building standalone decoupled UI's, but I don't think the project is in that state yet.

**Comment by dhylands** [comment]
I think that the spec describes most of the API. https://iot.mozilla.org/wot/#things-resource You're supposed to do a GET on /things and then use the href provided to work with a particular thing and not assume that /thingId will work

**Comment by benfrancis** [comment]
> I would argue those routes are mostly internal to the web interface. I don't see the value in adding swagger definitions to routes that are not part of a public API. It would allow building standalone decoupled UI's, but I don't think the project is in that state yet.

Those routes are in fact intended to be a public API, which you can request access to using OAuth. As Dave says, that API is documented in the proposed standard [Web Thing API](https://iot.mozilla.org/wot) but the specific URL paths are implementation specific. They are defined using a HATEOAS approach in the Web Thing Description which the consumer of the API is expected to parse.

Does this make it impossible to document the API using Swagger?

**Comment by charifmahmoudi** [comment]
Maybe auto-generated Swagger definition that will include implementation specific URL paths ?
