### ISSUE TITLE
Dynamically loading/unloading individual Adapter instances

### ISSUE THREAD

**Issue by bhagman** [WebThingsIO/gateway#852]
Now that [multiple Adapter instances](https://github.com/mozilla-iot/gateway/commit/5b90d519c050f327dfcdacf59c271c6e491945ae) are allowed, how can they be added/removed dynamically?

From what I can see, the only way to remove an Adapter instance is through the Adapter Addon - which means that to dynamically add a physical device connected to the gateway, the Adapter Addon will need to be unloaded and restarted.

Two ideas:
* allow Adapters to instantiate and remove Adapters (race conditions?)
* introduce a function in the Addon to maintain it's own Adapter instances.  Where and when this function is called, I'm not certain.

**Comment by mrstegeman** [comment]
@bhagman As an example, if you have an adapter that gets loaded automatically when a device is hotplugged, all it needs to do is call `addonManager.loadAdapter(this)` (such as [this](https://github.com/mozilla-iot/example-adapter/blob/master/example-adapter.js#L75)).

There is not currently a nice way to dynamically remove from within the add-on, but you could replicate what the [addon-manager-proxy is doing](https://github.com/mozilla-iot/gateway/blob/master/src/plugin/addon-manager-proxy.js#L129).

Is that helpful at all?
